// AUTO-GENERATED BY @sidebase/nuxt-auth
declare module '#auth' {
  const { getServerSession, getToken, NuxtAuthHandler }: typeof import('C:/Users/Basti/Documents/My_Websites/Handmade_Sites/Javascript-Projects/Nuxt-Projects/Meeovi_Framework/Ecosystem/base-app/node_modules/@sidebase/nuxt-auth/dist/runtime/server/services')
}
