
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'BlocksNewsletter': typeof import("../../app/components/blocks/Newsletter.vue").default
  'BlocksAgeverification': typeof import("../../app/components/blocks/ageverification.vue").default
  'BlocksAnnouncements': typeof import("../../app/components/blocks/announcements.vue").default
  'BlocksCopyright': typeof import("../../app/components/blocks/copyright.vue").default
  'BlocksEditor': typeof import("../../app/components/blocks/editor.vue").default
  'BlocksLogo': typeof import("../../app/components/blocks/logo.vue").default
  'BlocksUseDark': typeof import("../../app/components/blocks/useDark.vue").default
  'MenusBottomFooter': typeof import("../../app/components/menus/BottomFooter.vue").default
  'MenusFooterNav': typeof import("../../app/components/menus/FooterNav.vue").default
  'MenusLayoutNotifications': typeof import("../../app/components/menus/LayoutNotifications.vue").default
  'MenusLowerBar': typeof import("../../app/components/menus/LowerBar.vue").default
  'MenusEcosystemmenu': typeof import("../../app/components/menus/ecosystemmenu.vue").default
  'MenusLivebarLive': typeof import("../../app/components/menus/livebar/live.vue").default
  'MenusMobilesearch': typeof import("../../app/components/menus/mobilesearch.vue").default
  'MenusSellerbar': typeof import("../../app/components/menus/sellerbar.vue").default
  'MenusSidebarBottomsidebarmenu': typeof import("../../app/components/menus/sidebar/bottomsidebarmenu.vue").default
  'MenusSidebarDepartmentsmenu': typeof import("../../app/components/menus/sidebar/departmentsmenu.vue").default
  'MenusSidebarMyaccountmenu': typeof import("../../app/components/menus/sidebar/myaccountmenu.vue").default
  'MenusSidebarOutletsmenu': typeof import("../../app/components/menus/sidebar/outletsmenu.vue").default
  'MenusSidebarSidebartop': typeof import("../../app/components/menus/sidebar/sidebartop.vue").default
  'MenusSidebarSocialmenu': typeof import("../../app/components/menus/sidebar/socialmenu.vue").default
  'MenusSidebarTopmenu': typeof import("../../app/components/menus/sidebar/topmenu.vue").default
  'MenusSidebarnav': typeof import("../../app/components/menus/sidebarnav.vue").default
  'MenusSocialLeftmenu': typeof import("../../app/components/menus/social/leftmenu.vue").default
  'MenusTopmenu': typeof import("../../app/components/menus/topmenu.vue").default
  'MenusTopmenuCart': typeof import("../../app/components/menus/topmenu/cart.vue").default
  'MenusTopmenuMobilesearch': typeof import("../../app/components/menus/topmenu/mobilesearch.vue").default
  'MenusTopmenuMyaccounttopmenu': typeof import("../../app/components/menus/topmenu/myaccounttopmenu.vue").default
  'PagesHomepageAtaglance': typeof import("../../app/components/pages/homepage/ataglance.vue").default
  'PagesHomepageBlogcallout': typeof import("../../app/components/pages/homepage/blogcallout.vue").default
  'PagesHomepageBlogposts': typeof import("../../app/components/pages/homepage/blogposts.vue").default
  'PagesHomepageBookcallout': typeof import("../../app/components/pages/homepage/bookcallout.vue").default
  'PagesHomepageCallout': typeof import("../../app/components/pages/homepage/callout.vue").default
  'PagesHomepageHeaderslider': typeof import("../../app/components/pages/homepage/headerslider.vue").default
  'PagesHomepageHellobar': typeof import("../../app/components/pages/homepage/hellobar.vue").default
  'PagesHomepageIntro': typeof import("../../app/components/pages/homepage/intro.vue").default
  'PagesHomepageMusiccallout': typeof import("../../app/components/pages/homepage/musiccallout.vue").default
  'PagesHomepagePixanomycallout': typeof import("../../app/components/pages/homepage/pixanomycallout.vue").default
  'PagesHomepageRadiostationscallout': typeof import("../../app/components/pages/homepage/radiostationscallout.vue").default
  'PagesHomepageSectionscallout': typeof import("../../app/components/pages/homepage/sectionscallout.vue").default
  'PagesHomepageSpotlight': typeof import("../../app/components/pages/homepage/spotlight.vue").default
  'PagesHomepageTheatercallout': typeof import("../../app/components/pages/homepage/theatercallout.vue").default
  'PagesHomepageYardsale': typeof import("../../app/components/pages/homepage/yardsale.vue").default
  'PagesNotifications': typeof import("../../app/components/pages/notifications.vue").default
  'PagesOffline': typeof import("../../app/components/pages/offline.vue").default
  'PagesProfileArchives': typeof import("../../app/components/pages/profile/archives.vue").default
  'PagesProfileBookmarks': typeof import("../../app/components/pages/profile/bookmarks.vue").default
  'PagesProfileLikes': typeof import("../../app/components/pages/profile/likes.vue").default
  'PagesProfileMedia': typeof import("../../app/components/pages/profile/media.vue").default
  'PagesProfileReplies': typeof import("../../app/components/pages/profile/replies.vue").default
  'PagesUpload': typeof import("../../app/components/pages/upload.vue").default
  'AuthLogutButton': typeof import("../../layers/shared-app/app/components/auth/logutButton.vue").default
  'CommunicationChannels': typeof import("../../layers/shared-app/app/components/communication/channels.vue").default
  'CommunicationChat': typeof import("../../layers/shared-app/app/components/communication/chat.vue").default
  'CommunicationDirectory': typeof import("../../layers/shared-app/app/components/communication/directory.vue").default
  'CommunicationInvites': typeof import("../../layers/shared-app/app/components/communication/invites.vue").default
  'CommunicationMessages': typeof import("../../layers/shared-app/app/components/communication/messages.vue").default
  'CommunicationRooms': typeof import("../../layers/shared-app/app/components/communication/rooms.vue").default
  'CommunicationTeams': typeof import("../../layers/shared-app/app/components/communication/teams.vue").default
  'MediaNowPlaying': typeof import("../../layers/shared-app/app/components/media/nowPlaying.vue").default
  'MediaPlaylist': typeof import("../../layers/shared-app/app/components/media/playlist.vue").default
  'MediaRadioPlayer': typeof import("../../layers/shared-app/app/components/media/radioPlayer.vue").default
  'MediaVideoPlayer': typeof import("../../layers/shared-app/app/components/media/videoPlayer.vue").default
  'SearchAtomsBaseButton': typeof import("../../layers/shared-app/app/components/search/atoms/BaseButton.vue").default
  'SearchAtomsBaseCard': typeof import("../../layers/shared-app/app/components/search/atoms/BaseCard.vue").default
  'SearchAtomsBaseCheckbox': typeof import("../../layers/shared-app/app/components/search/atoms/BaseCheckbox.vue").default
  'SearchAtomsBaseLogo': typeof import("../../layers/shared-app/app/components/search/atoms/BaseLogo.vue").default
  'SearchAtomsBaseText': typeof import("../../layers/shared-app/app/components/search/atoms/BaseText.vue").default
  'SearchAtomsBaseTitle': typeof import("../../layers/shared-app/app/components/search/atoms/BaseTitle.vue").default
  'SearchAtomsDiscordIcon': typeof import("../../layers/shared-app/app/components/search/atoms/DiscordIcon.vue").default
  'SearchAtomsGithubIcon': typeof import("../../layers/shared-app/app/components/search/atoms/GithubIcon.vue").default
  'SearchAtomsHalfSolidStarIcon': typeof import("../../layers/shared-app/app/components/search/atoms/HalfSolidStarIcon.vue").default
  'SearchAtomsSelectArrow': typeof import("../../layers/shared-app/app/components/search/atoms/SelectArrow.vue").default
  'SearchAtomsSolidStarIcon': typeof import("../../layers/shared-app/app/components/search/atoms/SolidStarIcon.vue").default
  'SearchAtomsStarIcon': typeof import("../../layers/shared-app/app/components/search/atoms/StarIcon.vue").default
  'SearchAtomsTwitterIcon': typeof import("../../layers/shared-app/app/components/search/atoms/TwitterIcon.vue").default
  'SearchAtomsWebIcon': typeof import("../../layers/shared-app/app/components/search/atoms/WebIcon.vue").default
  'SearchAtomsXIcon': typeof import("../../layers/shared-app/app/components/search/atoms/XIcon.vue").default
  'SearchFeaturesAiSearch': typeof import("../../layers/shared-app/app/components/search/features/aiSearch.vue").default
  'SearchFeaturesAllSearch': typeof import("../../layers/shared-app/app/components/search/features/allSearch.vue").default
  'SearchFeaturesAutocomplete': typeof import("../../layers/shared-app/app/components/search/features/autocomplete.vue").default
  'SearchFeaturesImageSearch': typeof import("../../layers/shared-app/app/components/search/features/imageSearch.vue").default
  'SearchFeaturesVideoSearch': typeof import("../../layers/shared-app/app/components/search/features/videoSearch.vue").default
  'SearchFilters': typeof import("../../layers/shared-app/app/components/search/filters/filters.vue").default
  'SearchMoleculesBaseSelect': typeof import("../../layers/shared-app/app/components/search/molecules/BaseSelect.vue").default
  'SearchMoleculesPageNumber': typeof import("../../layers/shared-app/app/components/search/molecules/PageNumber.vue").default
  'SearchMoleculesRangeSlider': typeof import("../../layers/shared-app/app/components/search/molecules/RangeSlider.vue").default
  'SearchMoleculesSearchInput': typeof import("../../layers/shared-app/app/components/search/molecules/SearchInput.vue").default
  'SearchMoleculesSocialLink': typeof import("../../layers/shared-app/app/components/search/molecules/SocialLink.vue").default
  'SearchMoleculesStarRating': typeof import("../../layers/shared-app/app/components/search/molecules/StarRating.vue").default
  'SearchOrganismsLoadingIndicator': typeof import("../../layers/shared-app/app/components/search/organisms/LoadingIndicator.vue").default
  'SearchOrganismsMeiliSearchBar': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchBar.vue").default
  'SearchOrganismsMeiliSearchFacetFilter': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchFacetFilter.vue").default
  'SearchOrganismsMeiliSearchLoadingProvider': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchLoadingProvider.vue").default
  'SearchOrganismsMeiliSearchPagination': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchPagination.vue").default
  'SearchOrganismsMeiliSearchProvider': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchProvider.vue").default
  'SearchOrganismsMeiliSearchRangeFilter': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchRangeFilter.vue").default
  'SearchOrganismsMeiliSearchRatingFilter': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchRatingFilter.vue").default
  'SearchOrganismsMeiliSearchResults': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchResults.vue").default
  'SearchOrganismsMeiliSearchSorting': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchSorting.vue").default
  'SearchOrganismsMeiliSearchStats': typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchStats.vue").default
  'SearchOrganismsProductCard': typeof import("../../layers/shared-app/app/components/search/organisms/ProductCard.vue").default
  'SearchOrganismsTheNavbar': typeof import("../../layers/shared-app/app/components/search/organisms/TheNavbar.vue").default
  'SearchResultsAudioSearch': typeof import("../../layers/shared-app/app/components/search/results/audioSearch.vue").default
  'SearchResultsBooksSearch': typeof import("../../layers/shared-app/app/components/search/results/booksSearch.vue").default
  'SearchResultsFinanceSearch': typeof import("../../layers/shared-app/app/components/search/results/financeSearch.vue").default
  'SearchResultsImageSearch': typeof import("../../layers/shared-app/app/components/search/results/imageSearch.vue").default
  'SearchResultsMusicSearch': typeof import("../../layers/shared-app/app/components/search/results/musicSearch.vue").default
  'SearchResultsNewsSearch': typeof import("../../layers/shared-app/app/components/search/results/newsSearch.vue").default
  'SearchResultsSpaceSearch': typeof import("../../layers/shared-app/app/components/search/results/spaceSearch.vue").default
  'SearchResultsSpacesSearch': typeof import("../../layers/shared-app/app/components/search/results/spacesSearch.vue").default
  'SearchResultsTravelSearch': typeof import("../../layers/shared-app/app/components/search/results/travelSearch.vue").default
  'SearchResultsVideoSearch': typeof import("../../layers/shared-app/app/components/search/results/videoSearch.vue").default
  'Search': typeof import("../../layers/shared-app/app/components/search/search.vue").default
  'SearchTemplatesHomeTemplate': typeof import("../../layers/shared-app/app/components/search/templates/HomeTemplate.vue").default
  'SearchWidgetsClearRefinements': typeof import("../../layers/shared-app/app/components/search/widgets/ClearRefinements.vue").default
  'SearchWidgetsNoResults': typeof import("../../layers/shared-app/app/components/search/widgets/NoResults.vue").default
  'UiPageBuilder': typeof import("../../layers/shared-app/app/components/ui/PageBuilder.vue").default
  'UiFormsBooleanInput': typeof import("../../layers/shared-app/app/components/ui/forms/BooleanInput.vue").default
  'UiFormsDateTime': typeof import("../../layers/shared-app/app/components/ui/forms/DateTime.vue").default
  'UiFormsDirectusFormElement': typeof import("../../layers/shared-app/app/components/ui/forms/DirectusFormElement.vue").default
  'UiFormsDynamicTableElement': typeof import("../../layers/shared-app/app/components/ui/forms/DynamicTableElement.vue").default
  'UiFormsFileInput': typeof import("../../layers/shared-app/app/components/ui/forms/FileInput.vue").default
  'UiFormsRelationSelect': typeof import("../../layers/shared-app/app/components/ui/forms/RelationSelect.vue").default
  'UiFormsRepeaterInput': typeof import("../../layers/shared-app/app/components/ui/forms/RepeaterInput.vue").default
  'UiFormsSelectInput': typeof import("../../layers/shared-app/app/components/ui/forms/SelectInput.vue").default
  'UiFormsTextArea': typeof import("../../layers/shared-app/app/components/ui/forms/TextArea.vue").default
  'UiFormsTextInput': typeof import("../../layers/shared-app/app/components/ui/forms/TextInput.vue").default
  'UiFormsTiptapEditor': typeof import("../../layers/shared-app/app/components/ui/forms/TiptapEditor.vue").default
  'UiForms[collection]': typeof import("../../layers/shared-app/app/components/ui/forms/[collection].vue").default
  'FeaturesAttributes': typeof import("../../layers/seller-dashboard-app/app/components/features/attributes.vue").default
  'FeaturesIncentives': typeof import("../../layers/seller-dashboard-app/app/components/features/incentives.vue").default
  'FeaturesIntegrations': typeof import("../../layers/seller-dashboard-app/app/components/features/integrations.vue").default
  'FeaturesMedia': typeof import("../../layers/seller-dashboard-app/app/components/features/media.vue").default
  'FeaturesProducts': typeof import("../../layers/seller-dashboard-app/app/components/features/products.vue").default
  'FeaturesReviews': typeof import("../../layers/seller-dashboard-app/app/components/features/reviews.vue").default
  'FeaturesSettings': typeof import("../../layers/seller-dashboard-app/app/components/features/settings.vue").default
  'FeaturesSpaces': typeof import("../../layers/seller-dashboard-app/app/components/features/spaces.vue").default
  'MagicDrawer': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicDrawer/src/components/MagicDrawer.vue").default
  'MagicMenuChannel': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuChannel.vue").default
  'MagicMenuContent': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuContent.vue").default
  'MagicMenuFloat': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuFloat.vue").default
  'MagicMenuItem': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuItem.vue").default
  'MagicMenuProvider': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuProvider.vue").default
  'MagicMenuRemote': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuRemote.vue").default
  'MagicMenuTrigger': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuTrigger.vue").default
  'MagicMenuView': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuView.vue").default
  'MagicModal': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicModal/src/components/MagicModal.vue").default
  'MagicCommandContent': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandContent.vue").default
  'MagicCommandDrawer': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandDrawer.vue").default
  'MagicCommandItem': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandItem.vue").default
  'MagicCommandModal': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandModal.vue").default
  'MagicCommandProvider': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandProvider.vue").default
  'MagicCommandRenderer': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandRenderer.vue").default
  'MagicCommandTrigger': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandTrigger.vue").default
  'MagicCommandView': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandView.vue").default
  'MagicCookieItem': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieItem.vue").default
  'MagicCookieProvider': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieProvider.vue").default
  'MagicCookieView': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieView.vue").default
  'MagicMarquee': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMarquee/src/components/MagicMarquee.vue").default
  'MagicPlayerAudio': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudio.vue").default
  'MagicPlayerAudioControls': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudioControls.vue").default
  'MagicPlayerDisplayTime': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerDisplayTime.vue").default
  'MagicPlayerMuxPopover': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerMuxPopover.vue").default
  'MagicPlayerOverlay': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerOverlay.vue").default
  'MagicPlayerPoster': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerPoster.vue").default
  'MagicPlayerProvider': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerProvider.vue").default
  'MagicPlayerTimeline': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerTimeline.vue").default
  'MagicPlayerVideo': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideo.vue").default
  'MagicPlayerVideoControls': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideoControls.vue").default
  'MagicScrollCollision': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollCollision.vue").default
  'MagicScrollMotion': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollMotion.vue").default
  'MagicScrollProvider': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollProvider.vue").default
  'MagicScrollScene': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollScene.vue").default
  'AuthState': typeof import("../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue").default
  'Bouncer': typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Bouncer.vue").default
  'Can': typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Can.vue").default
  'Cannot': typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Cannot.vue").default
  'Primitive': typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Primitive").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'LCircle': typeof import("@vue-leaflet/vue-leaflet").LCircle
  'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet").LCircleMarker
  'LControl': typeof import("@vue-leaflet/vue-leaflet").LControl
  'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet").LControlAttribution
  'LControlLayers': typeof import("@vue-leaflet/vue-leaflet").LControlLayers
  'LControlScale': typeof import("@vue-leaflet/vue-leaflet").LControlScale
  'LControlZoom': typeof import("@vue-leaflet/vue-leaflet").LControlZoom
  'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet").LFeatureGroup
  'LGeoJson': typeof import("@vue-leaflet/vue-leaflet").LGeoJson
  'LIcon': typeof import("@vue-leaflet/vue-leaflet").LIcon
  'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet").LImageOverlay
  'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet").LLayerGroup
  'LMap': typeof import("@vue-leaflet/vue-leaflet").LMap
  'LMarker': typeof import("@vue-leaflet/vue-leaflet").LMarker
  'LPolygon': typeof import("@vue-leaflet/vue-leaflet").LPolygon
  'LPolyline': typeof import("@vue-leaflet/vue-leaflet").LPolyline
  'LPopup': typeof import("@vue-leaflet/vue-leaflet").LPopup
  'LRectangle': typeof import("@vue-leaflet/vue-leaflet").LRectangle
  'LTileLayer': typeof import("@vue-leaflet/vue-leaflet").LTileLayer
  'LTooltip': typeof import("@vue-leaflet/vue-leaflet").LTooltip
  'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet").LWmsTileLayer
  'MagicDraggable': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicDraggable/src/components/MagicDraggable.vue").default
  'MagicPie': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPie/src/components/MagicPie.vue").default
  'MagicNoise': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicNoise/src/components/MagicNoise.vue").default
  'MagicToastProvider': typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicToast/src/components/MagicToastProvider.vue").default
  'InstallButton': typeof import("../../node_modules/@nuxtjs/mcp-toolkit/dist/runtime/components/InstallButton.vue").default
  'TiptapEditorContent': typeof import("@tiptap/vue-3").EditorContent
  'TiptapFloatingMenu': typeof import("@tiptap/vue-3/menus").FloatingMenu
  'TiptapBubbleMenu': typeof import("@tiptap/vue-3/menus").BubbleMenu
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'SchemaOrgDebug': typeof import("@unhead/schema-org/vue").SchemaOrgDebug
  'SchemaOrgArticle': typeof import("@unhead/schema-org/vue").SchemaOrgArticle
  'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb
  'SchemaOrgComment': typeof import("@unhead/schema-org/vue").SchemaOrgComment
  'SchemaOrgEvent': typeof import("@unhead/schema-org/vue").SchemaOrgEvent
  'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment
  'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue").SchemaOrgHowTo
  'SchemaOrgImage': typeof import("@unhead/schema-org/vue").SchemaOrgImage
  'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting
  'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness
  'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue").SchemaOrgOrganization
  'SchemaOrgPerson': typeof import("@unhead/schema-org/vue").SchemaOrgPerson
  'SchemaOrgProduct': typeof import("@unhead/schema-org/vue").SchemaOrgProduct
  'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue").SchemaOrgQuestion
  'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue").SchemaOrgRecipe
  'SchemaOrgReview': typeof import("@unhead/schema-org/vue").SchemaOrgReview
  'SchemaOrgVideo': typeof import("@unhead/schema-org/vue").SchemaOrgVideo
  'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue").SchemaOrgWebPage
  'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue").SchemaOrgWebSite
  'SchemaOrgMovie': typeof import("@unhead/schema-org/vue").SchemaOrgMovie
  'SchemaOrgCourse': typeof import("@unhead/schema-org/vue").SchemaOrgCourse
  'SchemaOrgItemList': typeof import("@unhead/schema-org/vue").SchemaOrgItemList
  'SchemaOrgBook': typeof import("@unhead/schema-org/vue").SchemaOrgBook
  'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyBlocksNewsletter': LazyComponent<typeof import("../../app/components/blocks/Newsletter.vue").default>
  'LazyBlocksAgeverification': LazyComponent<typeof import("../../app/components/blocks/ageverification.vue").default>
  'LazyBlocksAnnouncements': LazyComponent<typeof import("../../app/components/blocks/announcements.vue").default>
  'LazyBlocksCopyright': LazyComponent<typeof import("../../app/components/blocks/copyright.vue").default>
  'LazyBlocksEditor': LazyComponent<typeof import("../../app/components/blocks/editor.vue").default>
  'LazyBlocksLogo': LazyComponent<typeof import("../../app/components/blocks/logo.vue").default>
  'LazyBlocksUseDark': LazyComponent<typeof import("../../app/components/blocks/useDark.vue").default>
  'LazyMenusBottomFooter': LazyComponent<typeof import("../../app/components/menus/BottomFooter.vue").default>
  'LazyMenusFooterNav': LazyComponent<typeof import("../../app/components/menus/FooterNav.vue").default>
  'LazyMenusLayoutNotifications': LazyComponent<typeof import("../../app/components/menus/LayoutNotifications.vue").default>
  'LazyMenusLowerBar': LazyComponent<typeof import("../../app/components/menus/LowerBar.vue").default>
  'LazyMenusEcosystemmenu': LazyComponent<typeof import("../../app/components/menus/ecosystemmenu.vue").default>
  'LazyMenusLivebarLive': LazyComponent<typeof import("../../app/components/menus/livebar/live.vue").default>
  'LazyMenusMobilesearch': LazyComponent<typeof import("../../app/components/menus/mobilesearch.vue").default>
  'LazyMenusSellerbar': LazyComponent<typeof import("../../app/components/menus/sellerbar.vue").default>
  'LazyMenusSidebarBottomsidebarmenu': LazyComponent<typeof import("../../app/components/menus/sidebar/bottomsidebarmenu.vue").default>
  'LazyMenusSidebarDepartmentsmenu': LazyComponent<typeof import("../../app/components/menus/sidebar/departmentsmenu.vue").default>
  'LazyMenusSidebarMyaccountmenu': LazyComponent<typeof import("../../app/components/menus/sidebar/myaccountmenu.vue").default>
  'LazyMenusSidebarOutletsmenu': LazyComponent<typeof import("../../app/components/menus/sidebar/outletsmenu.vue").default>
  'LazyMenusSidebarSidebartop': LazyComponent<typeof import("../../app/components/menus/sidebar/sidebartop.vue").default>
  'LazyMenusSidebarSocialmenu': LazyComponent<typeof import("../../app/components/menus/sidebar/socialmenu.vue").default>
  'LazyMenusSidebarTopmenu': LazyComponent<typeof import("../../app/components/menus/sidebar/topmenu.vue").default>
  'LazyMenusSidebarnav': LazyComponent<typeof import("../../app/components/menus/sidebarnav.vue").default>
  'LazyMenusSocialLeftmenu': LazyComponent<typeof import("../../app/components/menus/social/leftmenu.vue").default>
  'LazyMenusTopmenu': LazyComponent<typeof import("../../app/components/menus/topmenu.vue").default>
  'LazyMenusTopmenuCart': LazyComponent<typeof import("../../app/components/menus/topmenu/cart.vue").default>
  'LazyMenusTopmenuMobilesearch': LazyComponent<typeof import("../../app/components/menus/topmenu/mobilesearch.vue").default>
  'LazyMenusTopmenuMyaccounttopmenu': LazyComponent<typeof import("../../app/components/menus/topmenu/myaccounttopmenu.vue").default>
  'LazyPagesHomepageAtaglance': LazyComponent<typeof import("../../app/components/pages/homepage/ataglance.vue").default>
  'LazyPagesHomepageBlogcallout': LazyComponent<typeof import("../../app/components/pages/homepage/blogcallout.vue").default>
  'LazyPagesHomepageBlogposts': LazyComponent<typeof import("../../app/components/pages/homepage/blogposts.vue").default>
  'LazyPagesHomepageBookcallout': LazyComponent<typeof import("../../app/components/pages/homepage/bookcallout.vue").default>
  'LazyPagesHomepageCallout': LazyComponent<typeof import("../../app/components/pages/homepage/callout.vue").default>
  'LazyPagesHomepageHeaderslider': LazyComponent<typeof import("../../app/components/pages/homepage/headerslider.vue").default>
  'LazyPagesHomepageHellobar': LazyComponent<typeof import("../../app/components/pages/homepage/hellobar.vue").default>
  'LazyPagesHomepageIntro': LazyComponent<typeof import("../../app/components/pages/homepage/intro.vue").default>
  'LazyPagesHomepageMusiccallout': LazyComponent<typeof import("../../app/components/pages/homepage/musiccallout.vue").default>
  'LazyPagesHomepagePixanomycallout': LazyComponent<typeof import("../../app/components/pages/homepage/pixanomycallout.vue").default>
  'LazyPagesHomepageRadiostationscallout': LazyComponent<typeof import("../../app/components/pages/homepage/radiostationscallout.vue").default>
  'LazyPagesHomepageSectionscallout': LazyComponent<typeof import("../../app/components/pages/homepage/sectionscallout.vue").default>
  'LazyPagesHomepageSpotlight': LazyComponent<typeof import("../../app/components/pages/homepage/spotlight.vue").default>
  'LazyPagesHomepageTheatercallout': LazyComponent<typeof import("../../app/components/pages/homepage/theatercallout.vue").default>
  'LazyPagesHomepageYardsale': LazyComponent<typeof import("../../app/components/pages/homepage/yardsale.vue").default>
  'LazyPagesNotifications': LazyComponent<typeof import("../../app/components/pages/notifications.vue").default>
  'LazyPagesOffline': LazyComponent<typeof import("../../app/components/pages/offline.vue").default>
  'LazyPagesProfileArchives': LazyComponent<typeof import("../../app/components/pages/profile/archives.vue").default>
  'LazyPagesProfileBookmarks': LazyComponent<typeof import("../../app/components/pages/profile/bookmarks.vue").default>
  'LazyPagesProfileLikes': LazyComponent<typeof import("../../app/components/pages/profile/likes.vue").default>
  'LazyPagesProfileMedia': LazyComponent<typeof import("../../app/components/pages/profile/media.vue").default>
  'LazyPagesProfileReplies': LazyComponent<typeof import("../../app/components/pages/profile/replies.vue").default>
  'LazyPagesUpload': LazyComponent<typeof import("../../app/components/pages/upload.vue").default>
  'LazyAuthLogutButton': LazyComponent<typeof import("../../layers/shared-app/app/components/auth/logutButton.vue").default>
  'LazyCommunicationChannels': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/channels.vue").default>
  'LazyCommunicationChat': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/chat.vue").default>
  'LazyCommunicationDirectory': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/directory.vue").default>
  'LazyCommunicationInvites': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/invites.vue").default>
  'LazyCommunicationMessages': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/messages.vue").default>
  'LazyCommunicationRooms': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/rooms.vue").default>
  'LazyCommunicationTeams': LazyComponent<typeof import("../../layers/shared-app/app/components/communication/teams.vue").default>
  'LazyMediaNowPlaying': LazyComponent<typeof import("../../layers/shared-app/app/components/media/nowPlaying.vue").default>
  'LazyMediaPlaylist': LazyComponent<typeof import("../../layers/shared-app/app/components/media/playlist.vue").default>
  'LazyMediaRadioPlayer': LazyComponent<typeof import("../../layers/shared-app/app/components/media/radioPlayer.vue").default>
  'LazyMediaVideoPlayer': LazyComponent<typeof import("../../layers/shared-app/app/components/media/videoPlayer.vue").default>
  'LazySearchAtomsBaseButton': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/BaseButton.vue").default>
  'LazySearchAtomsBaseCard': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/BaseCard.vue").default>
  'LazySearchAtomsBaseCheckbox': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/BaseCheckbox.vue").default>
  'LazySearchAtomsBaseLogo': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/BaseLogo.vue").default>
  'LazySearchAtomsBaseText': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/BaseText.vue").default>
  'LazySearchAtomsBaseTitle': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/BaseTitle.vue").default>
  'LazySearchAtomsDiscordIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/DiscordIcon.vue").default>
  'LazySearchAtomsGithubIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/GithubIcon.vue").default>
  'LazySearchAtomsHalfSolidStarIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/HalfSolidStarIcon.vue").default>
  'LazySearchAtomsSelectArrow': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/SelectArrow.vue").default>
  'LazySearchAtomsSolidStarIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/SolidStarIcon.vue").default>
  'LazySearchAtomsStarIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/StarIcon.vue").default>
  'LazySearchAtomsTwitterIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/TwitterIcon.vue").default>
  'LazySearchAtomsWebIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/WebIcon.vue").default>
  'LazySearchAtomsXIcon': LazyComponent<typeof import("../../layers/shared-app/app/components/search/atoms/XIcon.vue").default>
  'LazySearchFeaturesAiSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/features/aiSearch.vue").default>
  'LazySearchFeaturesAllSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/features/allSearch.vue").default>
  'LazySearchFeaturesAutocomplete': LazyComponent<typeof import("../../layers/shared-app/app/components/search/features/autocomplete.vue").default>
  'LazySearchFeaturesImageSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/features/imageSearch.vue").default>
  'LazySearchFeaturesVideoSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/features/videoSearch.vue").default>
  'LazySearchFilters': LazyComponent<typeof import("../../layers/shared-app/app/components/search/filters/filters.vue").default>
  'LazySearchMoleculesBaseSelect': LazyComponent<typeof import("../../layers/shared-app/app/components/search/molecules/BaseSelect.vue").default>
  'LazySearchMoleculesPageNumber': LazyComponent<typeof import("../../layers/shared-app/app/components/search/molecules/PageNumber.vue").default>
  'LazySearchMoleculesRangeSlider': LazyComponent<typeof import("../../layers/shared-app/app/components/search/molecules/RangeSlider.vue").default>
  'LazySearchMoleculesSearchInput': LazyComponent<typeof import("../../layers/shared-app/app/components/search/molecules/SearchInput.vue").default>
  'LazySearchMoleculesSocialLink': LazyComponent<typeof import("../../layers/shared-app/app/components/search/molecules/SocialLink.vue").default>
  'LazySearchMoleculesStarRating': LazyComponent<typeof import("../../layers/shared-app/app/components/search/molecules/StarRating.vue").default>
  'LazySearchOrganismsLoadingIndicator': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/LoadingIndicator.vue").default>
  'LazySearchOrganismsMeiliSearchBar': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchBar.vue").default>
  'LazySearchOrganismsMeiliSearchFacetFilter': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchFacetFilter.vue").default>
  'LazySearchOrganismsMeiliSearchLoadingProvider': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchLoadingProvider.vue").default>
  'LazySearchOrganismsMeiliSearchPagination': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchPagination.vue").default>
  'LazySearchOrganismsMeiliSearchProvider': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchProvider.vue").default>
  'LazySearchOrganismsMeiliSearchRangeFilter': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchRangeFilter.vue").default>
  'LazySearchOrganismsMeiliSearchRatingFilter': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchRatingFilter.vue").default>
  'LazySearchOrganismsMeiliSearchResults': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchResults.vue").default>
  'LazySearchOrganismsMeiliSearchSorting': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchSorting.vue").default>
  'LazySearchOrganismsMeiliSearchStats': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/MeiliSearchStats.vue").default>
  'LazySearchOrganismsProductCard': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/ProductCard.vue").default>
  'LazySearchOrganismsTheNavbar': LazyComponent<typeof import("../../layers/shared-app/app/components/search/organisms/TheNavbar.vue").default>
  'LazySearchResultsAudioSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/audioSearch.vue").default>
  'LazySearchResultsBooksSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/booksSearch.vue").default>
  'LazySearchResultsFinanceSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/financeSearch.vue").default>
  'LazySearchResultsImageSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/imageSearch.vue").default>
  'LazySearchResultsMusicSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/musicSearch.vue").default>
  'LazySearchResultsNewsSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/newsSearch.vue").default>
  'LazySearchResultsSpaceSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/spaceSearch.vue").default>
  'LazySearchResultsSpacesSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/spacesSearch.vue").default>
  'LazySearchResultsTravelSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/travelSearch.vue").default>
  'LazySearchResultsVideoSearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/results/videoSearch.vue").default>
  'LazySearch': LazyComponent<typeof import("../../layers/shared-app/app/components/search/search.vue").default>
  'LazySearchTemplatesHomeTemplate': LazyComponent<typeof import("../../layers/shared-app/app/components/search/templates/HomeTemplate.vue").default>
  'LazySearchWidgetsClearRefinements': LazyComponent<typeof import("../../layers/shared-app/app/components/search/widgets/ClearRefinements.vue").default>
  'LazySearchWidgetsNoResults': LazyComponent<typeof import("../../layers/shared-app/app/components/search/widgets/NoResults.vue").default>
  'LazyUiPageBuilder': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/PageBuilder.vue").default>
  'LazyUiFormsBooleanInput': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/BooleanInput.vue").default>
  'LazyUiFormsDateTime': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/DateTime.vue").default>
  'LazyUiFormsDirectusFormElement': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/DirectusFormElement.vue").default>
  'LazyUiFormsDynamicTableElement': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/DynamicTableElement.vue").default>
  'LazyUiFormsFileInput': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/FileInput.vue").default>
  'LazyUiFormsRelationSelect': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/RelationSelect.vue").default>
  'LazyUiFormsRepeaterInput': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/RepeaterInput.vue").default>
  'LazyUiFormsSelectInput': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/SelectInput.vue").default>
  'LazyUiFormsTextArea': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/TextArea.vue").default>
  'LazyUiFormsTextInput': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/TextInput.vue").default>
  'LazyUiFormsTiptapEditor': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/TiptapEditor.vue").default>
  'LazyUiForms[collection]': LazyComponent<typeof import("../../layers/shared-app/app/components/ui/forms/[collection].vue").default>
  'LazyFeaturesAttributes': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/attributes.vue").default>
  'LazyFeaturesIncentives': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/incentives.vue").default>
  'LazyFeaturesIntegrations': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/integrations.vue").default>
  'LazyFeaturesMedia': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/media.vue").default>
  'LazyFeaturesProducts': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/products.vue").default>
  'LazyFeaturesReviews': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/reviews.vue").default>
  'LazyFeaturesSettings': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/settings.vue").default>
  'LazyFeaturesSpaces': LazyComponent<typeof import("../../layers/seller-dashboard-app/app/components/features/spaces.vue").default>
  'LazyMagicDrawer': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicDrawer/src/components/MagicDrawer.vue").default>
  'LazyMagicMenuChannel': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuChannel.vue").default>
  'LazyMagicMenuContent': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuContent.vue").default>
  'LazyMagicMenuFloat': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuFloat.vue").default>
  'LazyMagicMenuItem': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuItem.vue").default>
  'LazyMagicMenuProvider': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuProvider.vue").default>
  'LazyMagicMenuRemote': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuRemote.vue").default>
  'LazyMagicMenuTrigger': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuTrigger.vue").default>
  'LazyMagicMenuView': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuView.vue").default>
  'LazyMagicModal': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicModal/src/components/MagicModal.vue").default>
  'LazyMagicCommandContent': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandContent.vue").default>
  'LazyMagicCommandDrawer': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandDrawer.vue").default>
  'LazyMagicCommandItem': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandItem.vue").default>
  'LazyMagicCommandModal': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandModal.vue").default>
  'LazyMagicCommandProvider': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandProvider.vue").default>
  'LazyMagicCommandRenderer': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandRenderer.vue").default>
  'LazyMagicCommandTrigger': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandTrigger.vue").default>
  'LazyMagicCommandView': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandView.vue").default>
  'LazyMagicCookieItem': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieItem.vue").default>
  'LazyMagicCookieProvider': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieProvider.vue").default>
  'LazyMagicCookieView': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieView.vue").default>
  'LazyMagicMarquee': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicMarquee/src/components/MagicMarquee.vue").default>
  'LazyMagicPlayerAudio': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudio.vue").default>
  'LazyMagicPlayerAudioControls': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudioControls.vue").default>
  'LazyMagicPlayerDisplayTime': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerDisplayTime.vue").default>
  'LazyMagicPlayerMuxPopover': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerMuxPopover.vue").default>
  'LazyMagicPlayerOverlay': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerOverlay.vue").default>
  'LazyMagicPlayerPoster': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerPoster.vue").default>
  'LazyMagicPlayerProvider': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerProvider.vue").default>
  'LazyMagicPlayerTimeline': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerTimeline.vue").default>
  'LazyMagicPlayerVideo': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideo.vue").default>
  'LazyMagicPlayerVideoControls': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideoControls.vue").default>
  'LazyMagicScrollCollision': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollCollision.vue").default>
  'LazyMagicScrollMotion': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollMotion.vue").default>
  'LazyMagicScrollProvider': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollProvider.vue").default>
  'LazyMagicScrollScene': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollScene.vue").default>
  'LazyAuthState': LazyComponent<typeof import("../../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue").default>
  'LazyBouncer': LazyComponent<typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Bouncer.vue").default>
  'LazyCan': LazyComponent<typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Can.vue").default>
  'LazyCannot': LazyComponent<typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Cannot.vue").default>
  'LazyPrimitive': LazyComponent<typeof import("../../node_modules/nuxt-authorization/dist/runtime/components/Primitive").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazyLCircle': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LCircle>
  'LazyLCircleMarker': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LCircleMarker>
  'LazyLControl': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControl>
  'LazyLControlAttribution': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlAttribution>
  'LazyLControlLayers': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlLayers>
  'LazyLControlScale': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlScale>
  'LazyLControlZoom': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlZoom>
  'LazyLFeatureGroup': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LFeatureGroup>
  'LazyLGeoJson': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LGeoJson>
  'LazyLIcon': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LIcon>
  'LazyLImageOverlay': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LImageOverlay>
  'LazyLLayerGroup': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LLayerGroup>
  'LazyLMap': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LMap>
  'LazyLMarker': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LMarker>
  'LazyLPolygon': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LPolygon>
  'LazyLPolyline': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LPolyline>
  'LazyLPopup': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LPopup>
  'LazyLRectangle': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LRectangle>
  'LazyLTileLayer': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LTileLayer>
  'LazyLTooltip': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LTooltip>
  'LazyLWmsTileLayer': LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LWmsTileLayer>
  'LazyMagicDraggable': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicDraggable/src/components/MagicDraggable.vue").default>
  'LazyMagicPie': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicPie/src/components/MagicPie.vue").default>
  'LazyMagicNoise': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicNoise/src/components/MagicNoise.vue").default>
  'LazyMagicToastProvider': LazyComponent<typeof import("../../node_modules/@maas/vue-equipment/dist/plugins/MagicToast/src/components/MagicToastProvider.vue").default>
  'LazyInstallButton': LazyComponent<typeof import("../../node_modules/@nuxtjs/mcp-toolkit/dist/runtime/components/InstallButton.vue").default>
  'LazyTiptapEditorContent': LazyComponent<typeof import("@tiptap/vue-3").EditorContent>
  'LazyTiptapFloatingMenu': LazyComponent<typeof import("@tiptap/vue-3/menus").FloatingMenu>
  'LazyTiptapBubbleMenu': LazyComponent<typeof import("@tiptap/vue-3/menus").BubbleMenu>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazySchemaOrgDebug': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgDebug>
  'LazySchemaOrgArticle': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgArticle>
  'LazySchemaOrgBreadcrumb': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb>
  'LazySchemaOrgComment': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgComment>
  'LazySchemaOrgEvent': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgEvent>
  'LazySchemaOrgFoodEstablishment': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment>
  'LazySchemaOrgHowTo': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgHowTo>
  'LazySchemaOrgImage': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgImage>
  'LazySchemaOrgJobPosting': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting>
  'LazySchemaOrgLocalBusiness': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness>
  'LazySchemaOrgOrganization': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgOrganization>
  'LazySchemaOrgPerson': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgPerson>
  'LazySchemaOrgProduct': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgProduct>
  'LazySchemaOrgQuestion': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgQuestion>
  'LazySchemaOrgRecipe': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgRecipe>
  'LazySchemaOrgReview': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgReview>
  'LazySchemaOrgVideo': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgVideo>
  'LazySchemaOrgWebPage': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebPage>
  'LazySchemaOrgWebSite': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebSite>
  'LazySchemaOrgMovie': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgMovie>
  'LazySchemaOrgCourse': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgCourse>
  'LazySchemaOrgItemList': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgItemList>
  'LazySchemaOrgBook': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBook>
  'LazySchemaOrgSoftwareApp': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
