
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'CatalogProductAddAttribute': typeof import("../../app/components/catalog/product/add-attribute.vue").default
  'CatalogProductAddProductType': typeof import("../../app/components/catalog/product/add-product-type.vue").default
  'CatalogProductAddProduct': typeof import("../../app/components/catalog/product/add-product.vue").default
  'CatalogProductAddShowcase': typeof import("../../app/components/catalog/product/add-showcase.vue").default
  'CatalogProductAddStation': typeof import("../../app/components/catalog/product/add-station.vue").default
  'CatalogProductBestsellers': typeof import("../../app/components/catalog/product/bestsellers.vue").default
  'CatalogProductBidding': typeof import("../../app/components/catalog/product/bidding.vue").default
  'CatalogProductColorOptions': typeof import("../../app/components/catalog/product/colorOptions.vue").default
  'CatalogProductDeals': typeof import("../../app/components/catalog/product/deals.vue").default
  'CatalogProductExclusives': typeof import("../../app/components/catalog/product/exclusives.vue").default
  'CatalogProductFeaturedproducts': typeof import("../../app/components/catalog/product/featuredproducts.vue").default
  'CatalogProductGiftCard': typeof import("../../app/components/catalog/product/giftCard.vue").default
  'CatalogProductLatestproducts': typeof import("../../app/components/catalog/product/latestproducts.vue").default
  'CatalogProductCard': typeof import("../../app/components/catalog/product/productCard.vue").default
  'CatalogProductCompare': typeof import("../../app/components/catalog/product/productCompare.vue").default
  'CatalogProductCompareTable': typeof import("../../app/components/catalog/product/productCompareTable.vue").default
  'CatalogProductDetails': typeof import("../../app/components/catalog/product/productDetails.vue").default
  'CatalogProductFaqs': typeof import("../../app/components/catalog/product/productFaqs.vue").default
  'CatalogProductGallery': typeof import("../../app/components/catalog/product/productGallery.vue").default
  'CatalogProductQty': typeof import("../../app/components/catalog/product/productQty.vue").default
  'CatalogProductReviews': typeof import("../../app/components/catalog/product/productReviews.vue").default
  'CatalogProductSpecs': typeof import("../../app/components/catalog/product/productSpecs.vue").default
  'CatalogProductRadiostation': typeof import("../../app/components/catalog/product/radiostation.vue").default
  'CatalogProductRecentlyviewed': typeof import("../../app/components/catalog/product/recentlyviewed.vue").default
  'CatalogProductRelatedbrands': typeof import("../../app/components/catalog/product/relatedbrands.vue").default
  'CatalogProductRelatedproducts': typeof import("../../app/components/catalog/product/relatedproducts.vue").default
  'CatalogProductRelatedstations': typeof import("../../app/components/catalog/product/relatedstations.vue").default
  'CatalogProductShippingOptions': typeof import("../../app/components/catalog/product/shippingOptions.vue").default
  'CatalogProductSizeOptions': typeof import("../../app/components/catalog/product/sizeOptions.vue").default
  'CatalogProductUpdateAttributeSet': typeof import("../../app/components/catalog/product/update-attribute-set.vue").default
  'CatalogProductUpdateAttribute': typeof import("../../app/components/catalog/product/update-attribute.vue").default
  'CatalogProductUpdateProduct': typeof import("../../app/components/catalog/product/update-product.vue").default
  'CatalogProductUpdateShowcase': typeof import("../../app/components/catalog/product/update-showcase.vue").default
  'CatalogShopsRelatedstores': typeof import("../../app/components/catalog/shops/relatedstores.vue").default
  'CatalogShopsRestaurant': typeof import("../../app/components/catalog/shops/restaurant.vue").default
  'CatalogShopsStores': typeof import("../../app/components/catalog/shops/stores.vue").default
  'CatalogVendorBlocksBiggestcustomers': typeof import("../../app/components/catalog/vendor/blocks/biggestcustomers.vue").default
  'CatalogVendorBlocksLowestselling': typeof import("../../app/components/catalog/vendor/blocks/lowestselling.vue").default
  'CatalogVendorBlocksTopcategories': typeof import("../../app/components/catalog/vendor/blocks/topcategories.vue").default
  'CatalogVendorBlocksTopproducts': typeof import("../../app/components/catalog/vendor/blocks/topproducts.vue").default
  'CatalogVendorPagesAttributes': typeof import("../../app/components/catalog/vendor/pages/attributes.vue").default
  'CatalogVendorPagesCommissions': typeof import("../../app/components/catalog/vendor/pages/commissions.vue").default
  'CatalogVendorPagesCrm': typeof import("../../app/components/catalog/vendor/pages/crm.vue").default
  'CatalogVendorPagesDashboard': typeof import("../../app/components/catalog/vendor/pages/dashboard.vue").default
  'CatalogVendorPagesEmails': typeof import("../../app/components/catalog/vendor/pages/emails.vue").default
  'CatalogVendorPagesEnquiries': typeof import("../../app/components/catalog/vendor/pages/enquiries.vue").default
  'CatalogVendorPagesInvoices': typeof import("../../app/components/catalog/vendor/pages/invoices.vue").default
  'CatalogVendorPagesOrders': typeof import("../../app/components/catalog/vendor/pages/orders.vue").default
  'CatalogVendorPagesProducts': typeof import("../../app/components/catalog/vendor/pages/products.vue").default
  'CatalogVendorPagesReviews': typeof import("../../app/components/catalog/vendor/pages/reviews.vue").default
  'CatalogVendorPagesShipments': typeof import("../../app/components/catalog/vendor/pages/shipments.vue").default
  'CatalogVendorPagesStores': typeof import("../../app/components/catalog/vendor/pages/stores.vue").default
  'ContentBlocksBreadcrumbs': typeof import("../../app/components/content/blocks/breadcrumbs.vue").default
  'ContentBlocksCurrencySwitcher': typeof import("../../app/components/content/blocks/currencySwitcher.vue").default
  'ContentBlocksLanguageSwitcher': typeof import("../../app/components/content/blocks/languageSwitcher.vue").default
  'ContentBlocksVideoproduct': typeof import("../../app/components/content/blocks/videoproduct.vue").default
  'ContentPagesCheckout': typeof import("../../app/components/content/pages/checkout.vue").default
  'ContentPagesMeeoviGlobal': typeof import("../../app/components/content/pages/meeoviGlobal.vue").default
  'ContentPagesPickupLocations': typeof import("../../app/components/content/pages/pickup-locations.vue").default
  'ContentPagesShowcases': typeof import("../../app/components/content/pages/showcases.vue").default
  'ContentPagesSuccess': typeof import("../../app/components/content/pages/success.vue").default
  'MarketingAddBrand': typeof import("../../app/components/marketing/add-brand.vue").default
  'MarketingAddIncentive': typeof import("../../app/components/marketing/add-incentive.vue").default
  'MarketingPromotionsGiftcards': typeof import("../../app/components/marketing/promotions/giftcards.vue").default
  'MarketingPromotionsSubscriptions': typeof import("../../app/components/marketing/promotions/subscriptions.vue").default
  'MarketingUpdateIncentive': typeof import("../../app/components/marketing/update-incentive.vue").default
  'MenusLowernav': typeof import("../../app/components/menus/lowernav.vue").default
  'PartialsLocaleSelector': typeof import("../../app/components/partials/LocaleSelector.vue").default
  'PartialsShoppingCart': typeof import("../../app/components/partials/ShoppingCart.vue").default
  'PartialsStripePayment': typeof import("../../app/components/partials/StripePayment.vue").default
  'PartialsAddToCartBtn': typeof import("../../app/components/partials/addToCartBtn.vue").default
  'PartialsCartItem': typeof import("../../app/components/partials/cartItem.vue").default
  'PartialsCheckoutButton': typeof import("../../app/components/partials/checkoutButton.vue").default
  'PartialsCompareBtn': typeof import("../../app/components/partials/compareBtn.vue").default
  'PartialsRatings': typeof import("../../app/components/partials/ratings.vue").default
  'PartialsStoreCurrencySelector': typeof import("../../app/components/partials/store/CurrencySelector.vue").default
  'PartialsStoreSwitcher': typeof import("../../app/components/partials/store/StoreSwitcher.vue").default
  'RelatedBrandCard': typeof import("../../app/components/related/brandCard.vue").default
  'RelatedIncentiveCard': typeof import("../../app/components/related/incentiveCard.vue").default
  'RelatedInvoiceCard': typeof import("../../app/components/related/invoiceCard.vue").default
  'RelatedOrderCard': typeof import("../../app/components/related/orderCard.vue").default
  'RelatedRelatedproducts': typeof import("../../app/components/related/relatedproducts.vue").default
  'SalesIncentives': typeof import("../../app/components/sales/incentives.vue").default
  'SalesInvoices': typeof import("../../app/components/sales/invoices.vue").default
  'SalesOrders': typeof import("../../app/components/sales/orders.vue").default
  'SalesShipments': typeof import("../../app/components/sales/shipments.vue").default
  'SalesTransactions': typeof import("../../app/components/sales/transactions.vue").default
  'ShopAddShop': typeof import("../../app/components/shop/add-shop.vue").default
  'ShopCartItem': typeof import("../../app/components/shop/cart/cartItem.vue").default
  'ShopCartCheckout': typeof import("../../app/components/shop/cart/checkout.vue").default
  'ShopCheckoutStripeCardElement': typeof import("../../app/components/shop/checkout/StripeCardElement.vue").default
  'ShopCheckoutStripeCheckout': typeof import("../../app/components/shop/checkout/StripeCheckout.vue").default
  'ShopCheckoutAddressBilling': typeof import("../../app/components/shop/checkout/addressBilling.vue").default
  'ShopCheckoutAddressShipping': typeof import("../../app/components/shop/checkout/addressShipping.vue").default
  'ShopCheckoutCartProductItem': typeof import("../../app/components/shop/checkout/cart/ProductItem.vue").default
  'ShopCheckoutCartPromotionItem': typeof import("../../app/components/shop/checkout/cart/PromotionItem.vue").default
  'NuxtWelcome': typeof import("../../../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'NuxtPage': typeof import("../../../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyCatalogProductAddAttribute': LazyComponent<typeof import("../../app/components/catalog/product/add-attribute.vue").default>
  'LazyCatalogProductAddProductType': LazyComponent<typeof import("../../app/components/catalog/product/add-product-type.vue").default>
  'LazyCatalogProductAddProduct': LazyComponent<typeof import("../../app/components/catalog/product/add-product.vue").default>
  'LazyCatalogProductAddShowcase': LazyComponent<typeof import("../../app/components/catalog/product/add-showcase.vue").default>
  'LazyCatalogProductAddStation': LazyComponent<typeof import("../../app/components/catalog/product/add-station.vue").default>
  'LazyCatalogProductBestsellers': LazyComponent<typeof import("../../app/components/catalog/product/bestsellers.vue").default>
  'LazyCatalogProductBidding': LazyComponent<typeof import("../../app/components/catalog/product/bidding.vue").default>
  'LazyCatalogProductColorOptions': LazyComponent<typeof import("../../app/components/catalog/product/colorOptions.vue").default>
  'LazyCatalogProductDeals': LazyComponent<typeof import("../../app/components/catalog/product/deals.vue").default>
  'LazyCatalogProductExclusives': LazyComponent<typeof import("../../app/components/catalog/product/exclusives.vue").default>
  'LazyCatalogProductFeaturedproducts': LazyComponent<typeof import("../../app/components/catalog/product/featuredproducts.vue").default>
  'LazyCatalogProductGiftCard': LazyComponent<typeof import("../../app/components/catalog/product/giftCard.vue").default>
  'LazyCatalogProductLatestproducts': LazyComponent<typeof import("../../app/components/catalog/product/latestproducts.vue").default>
  'LazyCatalogProductCard': LazyComponent<typeof import("../../app/components/catalog/product/productCard.vue").default>
  'LazyCatalogProductCompare': LazyComponent<typeof import("../../app/components/catalog/product/productCompare.vue").default>
  'LazyCatalogProductCompareTable': LazyComponent<typeof import("../../app/components/catalog/product/productCompareTable.vue").default>
  'LazyCatalogProductDetails': LazyComponent<typeof import("../../app/components/catalog/product/productDetails.vue").default>
  'LazyCatalogProductFaqs': LazyComponent<typeof import("../../app/components/catalog/product/productFaqs.vue").default>
  'LazyCatalogProductGallery': LazyComponent<typeof import("../../app/components/catalog/product/productGallery.vue").default>
  'LazyCatalogProductQty': LazyComponent<typeof import("../../app/components/catalog/product/productQty.vue").default>
  'LazyCatalogProductReviews': LazyComponent<typeof import("../../app/components/catalog/product/productReviews.vue").default>
  'LazyCatalogProductSpecs': LazyComponent<typeof import("../../app/components/catalog/product/productSpecs.vue").default>
  'LazyCatalogProductRadiostation': LazyComponent<typeof import("../../app/components/catalog/product/radiostation.vue").default>
  'LazyCatalogProductRecentlyviewed': LazyComponent<typeof import("../../app/components/catalog/product/recentlyviewed.vue").default>
  'LazyCatalogProductRelatedbrands': LazyComponent<typeof import("../../app/components/catalog/product/relatedbrands.vue").default>
  'LazyCatalogProductRelatedproducts': LazyComponent<typeof import("../../app/components/catalog/product/relatedproducts.vue").default>
  'LazyCatalogProductRelatedstations': LazyComponent<typeof import("../../app/components/catalog/product/relatedstations.vue").default>
  'LazyCatalogProductShippingOptions': LazyComponent<typeof import("../../app/components/catalog/product/shippingOptions.vue").default>
  'LazyCatalogProductSizeOptions': LazyComponent<typeof import("../../app/components/catalog/product/sizeOptions.vue").default>
  'LazyCatalogProductUpdateAttributeSet': LazyComponent<typeof import("../../app/components/catalog/product/update-attribute-set.vue").default>
  'LazyCatalogProductUpdateAttribute': LazyComponent<typeof import("../../app/components/catalog/product/update-attribute.vue").default>
  'LazyCatalogProductUpdateProduct': LazyComponent<typeof import("../../app/components/catalog/product/update-product.vue").default>
  'LazyCatalogProductUpdateShowcase': LazyComponent<typeof import("../../app/components/catalog/product/update-showcase.vue").default>
  'LazyCatalogShopsRelatedstores': LazyComponent<typeof import("../../app/components/catalog/shops/relatedstores.vue").default>
  'LazyCatalogShopsRestaurant': LazyComponent<typeof import("../../app/components/catalog/shops/restaurant.vue").default>
  'LazyCatalogShopsStores': LazyComponent<typeof import("../../app/components/catalog/shops/stores.vue").default>
  'LazyCatalogVendorBlocksBiggestcustomers': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/biggestcustomers.vue").default>
  'LazyCatalogVendorBlocksLowestselling': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/lowestselling.vue").default>
  'LazyCatalogVendorBlocksTopcategories': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/topcategories.vue").default>
  'LazyCatalogVendorBlocksTopproducts': LazyComponent<typeof import("../../app/components/catalog/vendor/blocks/topproducts.vue").default>
  'LazyCatalogVendorPagesAttributes': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/attributes.vue").default>
  'LazyCatalogVendorPagesCommissions': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/commissions.vue").default>
  'LazyCatalogVendorPagesCrm': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/crm.vue").default>
  'LazyCatalogVendorPagesDashboard': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/dashboard.vue").default>
  'LazyCatalogVendorPagesEmails': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/emails.vue").default>
  'LazyCatalogVendorPagesEnquiries': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/enquiries.vue").default>
  'LazyCatalogVendorPagesInvoices': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/invoices.vue").default>
  'LazyCatalogVendorPagesOrders': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/orders.vue").default>
  'LazyCatalogVendorPagesProducts': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/products.vue").default>
  'LazyCatalogVendorPagesReviews': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/reviews.vue").default>
  'LazyCatalogVendorPagesShipments': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/shipments.vue").default>
  'LazyCatalogVendorPagesStores': LazyComponent<typeof import("../../app/components/catalog/vendor/pages/stores.vue").default>
  'LazyContentBlocksBreadcrumbs': LazyComponent<typeof import("../../app/components/content/blocks/breadcrumbs.vue").default>
  'LazyContentBlocksCurrencySwitcher': LazyComponent<typeof import("../../app/components/content/blocks/currencySwitcher.vue").default>
  'LazyContentBlocksLanguageSwitcher': LazyComponent<typeof import("../../app/components/content/blocks/languageSwitcher.vue").default>
  'LazyContentBlocksVideoproduct': LazyComponent<typeof import("../../app/components/content/blocks/videoproduct.vue").default>
  'LazyContentPagesCheckout': LazyComponent<typeof import("../../app/components/content/pages/checkout.vue").default>
  'LazyContentPagesMeeoviGlobal': LazyComponent<typeof import("../../app/components/content/pages/meeoviGlobal.vue").default>
  'LazyContentPagesPickupLocations': LazyComponent<typeof import("../../app/components/content/pages/pickup-locations.vue").default>
  'LazyContentPagesShowcases': LazyComponent<typeof import("../../app/components/content/pages/showcases.vue").default>
  'LazyContentPagesSuccess': LazyComponent<typeof import("../../app/components/content/pages/success.vue").default>
  'LazyMarketingAddBrand': LazyComponent<typeof import("../../app/components/marketing/add-brand.vue").default>
  'LazyMarketingAddIncentive': LazyComponent<typeof import("../../app/components/marketing/add-incentive.vue").default>
  'LazyMarketingPromotionsGiftcards': LazyComponent<typeof import("../../app/components/marketing/promotions/giftcards.vue").default>
  'LazyMarketingPromotionsSubscriptions': LazyComponent<typeof import("../../app/components/marketing/promotions/subscriptions.vue").default>
  'LazyMarketingUpdateIncentive': LazyComponent<typeof import("../../app/components/marketing/update-incentive.vue").default>
  'LazyMenusLowernav': LazyComponent<typeof import("../../app/components/menus/lowernav.vue").default>
  'LazyPartialsLocaleSelector': LazyComponent<typeof import("../../app/components/partials/LocaleSelector.vue").default>
  'LazyPartialsShoppingCart': LazyComponent<typeof import("../../app/components/partials/ShoppingCart.vue").default>
  'LazyPartialsStripePayment': LazyComponent<typeof import("../../app/components/partials/StripePayment.vue").default>
  'LazyPartialsAddToCartBtn': LazyComponent<typeof import("../../app/components/partials/addToCartBtn.vue").default>
  'LazyPartialsCartItem': LazyComponent<typeof import("../../app/components/partials/cartItem.vue").default>
  'LazyPartialsCheckoutButton': LazyComponent<typeof import("../../app/components/partials/checkoutButton.vue").default>
  'LazyPartialsCompareBtn': LazyComponent<typeof import("../../app/components/partials/compareBtn.vue").default>
  'LazyPartialsRatings': LazyComponent<typeof import("../../app/components/partials/ratings.vue").default>
  'LazyPartialsStoreCurrencySelector': LazyComponent<typeof import("../../app/components/partials/store/CurrencySelector.vue").default>
  'LazyPartialsStoreSwitcher': LazyComponent<typeof import("../../app/components/partials/store/StoreSwitcher.vue").default>
  'LazyRelatedBrandCard': LazyComponent<typeof import("../../app/components/related/brandCard.vue").default>
  'LazyRelatedIncentiveCard': LazyComponent<typeof import("../../app/components/related/incentiveCard.vue").default>
  'LazyRelatedInvoiceCard': LazyComponent<typeof import("../../app/components/related/invoiceCard.vue").default>
  'LazyRelatedOrderCard': LazyComponent<typeof import("../../app/components/related/orderCard.vue").default>
  'LazyRelatedRelatedproducts': LazyComponent<typeof import("../../app/components/related/relatedproducts.vue").default>
  'LazySalesIncentives': LazyComponent<typeof import("../../app/components/sales/incentives.vue").default>
  'LazySalesInvoices': LazyComponent<typeof import("../../app/components/sales/invoices.vue").default>
  'LazySalesOrders': LazyComponent<typeof import("../../app/components/sales/orders.vue").default>
  'LazySalesShipments': LazyComponent<typeof import("../../app/components/sales/shipments.vue").default>
  'LazySalesTransactions': LazyComponent<typeof import("../../app/components/sales/transactions.vue").default>
  'LazyShopAddShop': LazyComponent<typeof import("../../app/components/shop/add-shop.vue").default>
  'LazyShopCartItem': LazyComponent<typeof import("../../app/components/shop/cart/cartItem.vue").default>
  'LazyShopCartCheckout': LazyComponent<typeof import("../../app/components/shop/cart/checkout.vue").default>
  'LazyShopCheckoutStripeCardElement': LazyComponent<typeof import("../../app/components/shop/checkout/StripeCardElement.vue").default>
  'LazyShopCheckoutStripeCheckout': LazyComponent<typeof import("../../app/components/shop/checkout/StripeCheckout.vue").default>
  'LazyShopCheckoutAddressBilling': LazyComponent<typeof import("../../app/components/shop/checkout/addressBilling.vue").default>
  'LazyShopCheckoutAddressShipping': LazyComponent<typeof import("../../app/components/shop/checkout/addressShipping.vue").default>
  'LazyShopCheckoutCartProductItem': LazyComponent<typeof import("../../app/components/shop/checkout/cart/ProductItem.vue").default>
  'LazyShopCheckoutCartPromotionItem': LazyComponent<typeof import("../../app/components/shop/checkout/cart/PromotionItem.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyNuxtPage': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
