// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/create-checkout-session': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-checkout-session.post').default>>>>
    }
    '/api/stripe-webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stripe-webhook.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}