<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'

const props = withDefaults(defineProps<{
  modelValue?: any
  field: string
  label?: string
  options?: Record<string, any>
  multiple?: boolean
  required?: boolean
  width?: string | null
  autoGenerated?: boolean
}>(), {
  options: {},
  label: '',
  multiple: false,
  required: false,
  width: null,
  autoGenerated: false,
})

const emit = defineEmits(['update:modelValue'])

const items = ref<Array<{ title: string; value: any }>>([])
const loading = ref(false)

const selectValue = computed({
  get() {
    // Keep shape consistent: multiple -> array, single -> value
    if (props.multiple) return props.modelValue ?? []
    return props.modelValue ?? null
  },
  set(v) {
    emit('update:modelValue', v)
  }
})

const nuxt = useNuxtApp() as any

const getCollectionFromOptions = (opts: any) => {
  if (!opts) return null
  return opts.collection || opts.collectionField || opts.collection_name || opts.collectionName || opts.collection?.name || opts.collection?.collection || null
}

const displayCandidates = (item: any) => {
  return item?.title || item?.name || item?.label || item?.slug || item?.id || JSON.stringify(item)
}

const fetchOptions = async () => {
  const opts = props.options ?? {}
  const collection = getCollectionFromOptions(opts) || opts?.related_collection || opts?.relation || null
  if (!collection) return
  loading.value = true
  try {
    const { $directus, $readItems } = nuxt as any
    const resp = await $directus.request($readItems(collection, { limit: 200, fields: ['id', opts?.display || 'title'] }))
    // many $readItems responses return { data: [...] } or an array directly
    const data = resp?.data ?? resp ?? []
    items.value = (data || []).map((d: any) => ({ title: d[opts?.display] || displayCandidates(d), value: d.id }))
  } catch (e) {
    console.error('RelationSelect: failed to fetch options', e)
  } finally {
    loading.value = false
  }
}

onMounted(fetchOptions)

watch(() => props.options, fetchOptions, { immediate: true })
</script>

<template>
  <div :style="'width: ' + (props.width === 'full' ? '100%' : '50%') + '; display:flex; align-items:center; gap:8px'">
    <v-select
      :name="props.field"
      v-model="selectValue"
      :items="items"
      :label="props.label || props.field"
      :required="props.required"
      :multiple="props.multiple"
      variant="solo-inverted"
      density="compact"
      style="flex:1"
    />
    <span v-if="props.autoGenerated" class="auto-badge">Auto</span>
  </div>
</template>

<style scoped>
.auto-badge{font-size:12px;padding:4px 6px;border-radius:4px;background:#eee;color:#333}
</style>
