
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const BlocksNewsletter: typeof import("../app/components/blocks/Newsletter.vue").default
export const BlocksAgeverification: typeof import("../app/components/blocks/ageverification.vue").default
export const BlocksAnnouncements: typeof import("../app/components/blocks/announcements.vue").default
export const BlocksCopyright: typeof import("../app/components/blocks/copyright.vue").default
export const BlocksEditor: typeof import("../app/components/blocks/editor.vue").default
export const BlocksLogo: typeof import("../app/components/blocks/logo.vue").default
export const BlocksUseDark: typeof import("../app/components/blocks/useDark.vue").default
export const MenusBottomFooter: typeof import("../app/components/menus/BottomFooter.vue").default
export const MenusFooterNav: typeof import("../app/components/menus/FooterNav.vue").default
export const MenusLayoutNotifications: typeof import("../app/components/menus/LayoutNotifications.vue").default
export const MenusLowerBar: typeof import("../app/components/menus/LowerBar.vue").default
export const MenusEcosystemmenu: typeof import("../app/components/menus/ecosystemmenu.vue").default
export const MenusLivebarLive: typeof import("../app/components/menus/livebar/live.vue").default
export const MenusMobilesearch: typeof import("../app/components/menus/mobilesearch.vue").default
export const MenusSellerbar: typeof import("../app/components/menus/sellerbar.vue").default
export const MenusSidebarBottomsidebarmenu: typeof import("../app/components/menus/sidebar/bottomsidebarmenu.vue").default
export const MenusSidebarDepartmentsmenu: typeof import("../app/components/menus/sidebar/departmentsmenu.vue").default
export const MenusSidebarMyaccountmenu: typeof import("../app/components/menus/sidebar/myaccountmenu.vue").default
export const MenusSidebarOutletsmenu: typeof import("../app/components/menus/sidebar/outletsmenu.vue").default
export const MenusSidebarSidebartop: typeof import("../app/components/menus/sidebar/sidebartop.vue").default
export const MenusSidebarSocialmenu: typeof import("../app/components/menus/sidebar/socialmenu.vue").default
export const MenusSidebarTopmenu: typeof import("../app/components/menus/sidebar/topmenu.vue").default
export const MenusSidebarnav: typeof import("../app/components/menus/sidebarnav.vue").default
export const MenusSocialLeftmenu: typeof import("../app/components/menus/social/leftmenu.vue").default
export const MenusTopmenu: typeof import("../app/components/menus/topmenu.vue").default
export const MenusTopmenuCart: typeof import("../app/components/menus/topmenu/cart.vue").default
export const MenusTopmenuMobilesearch: typeof import("../app/components/menus/topmenu/mobilesearch.vue").default
export const MenusTopmenuMyaccounttopmenu: typeof import("../app/components/menus/topmenu/myaccounttopmenu.vue").default
export const PagesHomepageAtaglance: typeof import("../app/components/pages/homepage/ataglance.vue").default
export const PagesHomepageBlogcallout: typeof import("../app/components/pages/homepage/blogcallout.vue").default
export const PagesHomepageBlogposts: typeof import("../app/components/pages/homepage/blogposts.vue").default
export const PagesHomepageBookcallout: typeof import("../app/components/pages/homepage/bookcallout.vue").default
export const PagesHomepageCallout: typeof import("../app/components/pages/homepage/callout.vue").default
export const PagesHomepageHeaderslider: typeof import("../app/components/pages/homepage/headerslider.vue").default
export const PagesHomepageHellobar: typeof import("../app/components/pages/homepage/hellobar.vue").default
export const PagesHomepageIntro: typeof import("../app/components/pages/homepage/intro.vue").default
export const PagesHomepageMusiccallout: typeof import("../app/components/pages/homepage/musiccallout.vue").default
export const PagesHomepagePixanomycallout: typeof import("../app/components/pages/homepage/pixanomycallout.vue").default
export const PagesHomepageRadiostationscallout: typeof import("../app/components/pages/homepage/radiostationscallout.vue").default
export const PagesHomepageSectionscallout: typeof import("../app/components/pages/homepage/sectionscallout.vue").default
export const PagesHomepageSpotlight: typeof import("../app/components/pages/homepage/spotlight.vue").default
export const PagesHomepageTheatercallout: typeof import("../app/components/pages/homepage/theatercallout.vue").default
export const PagesHomepageYardsale: typeof import("../app/components/pages/homepage/yardsale.vue").default
export const PagesNotifications: typeof import("../app/components/pages/notifications.vue").default
export const PagesOffline: typeof import("../app/components/pages/offline.vue").default
export const PagesProfileArchives: typeof import("../app/components/pages/profile/archives.vue").default
export const PagesProfileBookmarks: typeof import("../app/components/pages/profile/bookmarks.vue").default
export const PagesProfileLikes: typeof import("../app/components/pages/profile/likes.vue").default
export const PagesProfileMedia: typeof import("../app/components/pages/profile/media.vue").default
export const PagesProfileReplies: typeof import("../app/components/pages/profile/replies.vue").default
export const PagesUpload: typeof import("../app/components/pages/upload.vue").default
export const AuthLogutButton: typeof import("../layers/shared-app/app/components/auth/logutButton.vue").default
export const CommunicationChannels: typeof import("../layers/shared-app/app/components/communication/channels.vue").default
export const CommunicationChat: typeof import("../layers/shared-app/app/components/communication/chat.vue").default
export const CommunicationDirectory: typeof import("../layers/shared-app/app/components/communication/directory.vue").default
export const CommunicationInvites: typeof import("../layers/shared-app/app/components/communication/invites.vue").default
export const CommunicationMessages: typeof import("../layers/shared-app/app/components/communication/messages.vue").default
export const CommunicationRooms: typeof import("../layers/shared-app/app/components/communication/rooms.vue").default
export const CommunicationTeams: typeof import("../layers/shared-app/app/components/communication/teams.vue").default
export const MediaNowPlaying: typeof import("../layers/shared-app/app/components/media/nowPlaying.vue").default
export const MediaPlaylist: typeof import("../layers/shared-app/app/components/media/playlist.vue").default
export const MediaRadioPlayer: typeof import("../layers/shared-app/app/components/media/radioPlayer.vue").default
export const MediaVideoPlayer: typeof import("../layers/shared-app/app/components/media/videoPlayer.vue").default
export const SearchAtomsBaseButton: typeof import("../layers/shared-app/app/components/search/atoms/BaseButton.vue").default
export const SearchAtomsBaseCard: typeof import("../layers/shared-app/app/components/search/atoms/BaseCard.vue").default
export const SearchAtomsBaseCheckbox: typeof import("../layers/shared-app/app/components/search/atoms/BaseCheckbox.vue").default
export const SearchAtomsBaseLogo: typeof import("../layers/shared-app/app/components/search/atoms/BaseLogo.vue").default
export const SearchAtomsBaseText: typeof import("../layers/shared-app/app/components/search/atoms/BaseText.vue").default
export const SearchAtomsBaseTitle: typeof import("../layers/shared-app/app/components/search/atoms/BaseTitle.vue").default
export const SearchAtomsDiscordIcon: typeof import("../layers/shared-app/app/components/search/atoms/DiscordIcon.vue").default
export const SearchAtomsGithubIcon: typeof import("../layers/shared-app/app/components/search/atoms/GithubIcon.vue").default
export const SearchAtomsHalfSolidStarIcon: typeof import("../layers/shared-app/app/components/search/atoms/HalfSolidStarIcon.vue").default
export const SearchAtomsSelectArrow: typeof import("../layers/shared-app/app/components/search/atoms/SelectArrow.vue").default
export const SearchAtomsSolidStarIcon: typeof import("../layers/shared-app/app/components/search/atoms/SolidStarIcon.vue").default
export const SearchAtomsStarIcon: typeof import("../layers/shared-app/app/components/search/atoms/StarIcon.vue").default
export const SearchAtomsTwitterIcon: typeof import("../layers/shared-app/app/components/search/atoms/TwitterIcon.vue").default
export const SearchAtomsWebIcon: typeof import("../layers/shared-app/app/components/search/atoms/WebIcon.vue").default
export const SearchAtomsXIcon: typeof import("../layers/shared-app/app/components/search/atoms/XIcon.vue").default
export const SearchFeaturesAiSearch: typeof import("../layers/shared-app/app/components/search/features/aiSearch.vue").default
export const SearchFeaturesAllSearch: typeof import("../layers/shared-app/app/components/search/features/allSearch.vue").default
export const SearchFeaturesAutocomplete: typeof import("../layers/shared-app/app/components/search/features/autocomplete.vue").default
export const SearchFeaturesImageSearch: typeof import("../layers/shared-app/app/components/search/features/imageSearch.vue").default
export const SearchFeaturesVideoSearch: typeof import("../layers/shared-app/app/components/search/features/videoSearch.vue").default
export const SearchFilters: typeof import("../layers/shared-app/app/components/search/filters/filters.vue").default
export const SearchMoleculesBaseSelect: typeof import("../layers/shared-app/app/components/search/molecules/BaseSelect.vue").default
export const SearchMoleculesPageNumber: typeof import("../layers/shared-app/app/components/search/molecules/PageNumber.vue").default
export const SearchMoleculesRangeSlider: typeof import("../layers/shared-app/app/components/search/molecules/RangeSlider.vue").default
export const SearchMoleculesSearchInput: typeof import("../layers/shared-app/app/components/search/molecules/SearchInput.vue").default
export const SearchMoleculesSocialLink: typeof import("../layers/shared-app/app/components/search/molecules/SocialLink.vue").default
export const SearchMoleculesStarRating: typeof import("../layers/shared-app/app/components/search/molecules/StarRating.vue").default
export const SearchOrganismsLoadingIndicator: typeof import("../layers/shared-app/app/components/search/organisms/LoadingIndicator.vue").default
export const SearchOrganismsMeiliSearchBar: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchBar.vue").default
export const SearchOrganismsMeiliSearchFacetFilter: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchFacetFilter.vue").default
export const SearchOrganismsMeiliSearchLoadingProvider: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchLoadingProvider.vue").default
export const SearchOrganismsMeiliSearchPagination: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchPagination.vue").default
export const SearchOrganismsMeiliSearchProvider: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchProvider.vue").default
export const SearchOrganismsMeiliSearchRangeFilter: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchRangeFilter.vue").default
export const SearchOrganismsMeiliSearchRatingFilter: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchRatingFilter.vue").default
export const SearchOrganismsMeiliSearchResults: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchResults.vue").default
export const SearchOrganismsMeiliSearchSorting: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchSorting.vue").default
export const SearchOrganismsMeiliSearchStats: typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchStats.vue").default
export const SearchOrganismsProductCard: typeof import("../layers/shared-app/app/components/search/organisms/ProductCard.vue").default
export const SearchOrganismsTheNavbar: typeof import("../layers/shared-app/app/components/search/organisms/TheNavbar.vue").default
export const SearchResultsAudioSearch: typeof import("../layers/shared-app/app/components/search/results/audioSearch.vue").default
export const SearchResultsBooksSearch: typeof import("../layers/shared-app/app/components/search/results/booksSearch.vue").default
export const SearchResultsFinanceSearch: typeof import("../layers/shared-app/app/components/search/results/financeSearch.vue").default
export const SearchResultsImageSearch: typeof import("../layers/shared-app/app/components/search/results/imageSearch.vue").default
export const SearchResultsMusicSearch: typeof import("../layers/shared-app/app/components/search/results/musicSearch.vue").default
export const SearchResultsNewsSearch: typeof import("../layers/shared-app/app/components/search/results/newsSearch.vue").default
export const SearchResultsSpaceSearch: typeof import("../layers/shared-app/app/components/search/results/spaceSearch.vue").default
export const SearchResultsSpacesSearch: typeof import("../layers/shared-app/app/components/search/results/spacesSearch.vue").default
export const SearchResultsTravelSearch: typeof import("../layers/shared-app/app/components/search/results/travelSearch.vue").default
export const SearchResultsVideoSearch: typeof import("../layers/shared-app/app/components/search/results/videoSearch.vue").default
export const Search: typeof import("../layers/shared-app/app/components/search/search.vue").default
export const SearchTemplatesHomeTemplate: typeof import("../layers/shared-app/app/components/search/templates/HomeTemplate.vue").default
export const SearchWidgetsClearRefinements: typeof import("../layers/shared-app/app/components/search/widgets/ClearRefinements.vue").default
export const SearchWidgetsNoResults: typeof import("../layers/shared-app/app/components/search/widgets/NoResults.vue").default
export const UiPageBuilder: typeof import("../layers/shared-app/app/components/ui/PageBuilder.vue").default
export const UiFormsBooleanInput: typeof import("../layers/shared-app/app/components/ui/forms/BooleanInput.vue").default
export const UiFormsDateTime: typeof import("../layers/shared-app/app/components/ui/forms/DateTime.vue").default
export const UiFormsDirectusFormElement: typeof import("../layers/shared-app/app/components/ui/forms/DirectusFormElement.vue").default
export const UiFormsDynamicTableElement: typeof import("../layers/shared-app/app/components/ui/forms/DynamicTableElement.vue").default
export const UiFormsFileInput: typeof import("../layers/shared-app/app/components/ui/forms/FileInput.vue").default
export const UiFormsRelationSelect: typeof import("../layers/shared-app/app/components/ui/forms/RelationSelect.vue").default
export const UiFormsRepeaterInput: typeof import("../layers/shared-app/app/components/ui/forms/RepeaterInput.vue").default
export const UiFormsSelectInput: typeof import("../layers/shared-app/app/components/ui/forms/SelectInput.vue").default
export const UiFormsTextArea: typeof import("../layers/shared-app/app/components/ui/forms/TextArea.vue").default
export const UiFormsTextInput: typeof import("../layers/shared-app/app/components/ui/forms/TextInput.vue").default
export const UiFormsTiptapEditor: typeof import("../layers/shared-app/app/components/ui/forms/TiptapEditor.vue").default
export const UiForms[collection]: typeof import("../layers/shared-app/app/components/ui/forms/[collection].vue").default
export const FeaturesAttributes: typeof import("../layers/seller-dashboard-app/app/components/features/attributes.vue").default
export const FeaturesIncentives: typeof import("../layers/seller-dashboard-app/app/components/features/incentives.vue").default
export const FeaturesIntegrations: typeof import("../layers/seller-dashboard-app/app/components/features/integrations.vue").default
export const FeaturesMedia: typeof import("../layers/seller-dashboard-app/app/components/features/media.vue").default
export const FeaturesProducts: typeof import("../layers/seller-dashboard-app/app/components/features/products.vue").default
export const FeaturesReviews: typeof import("../layers/seller-dashboard-app/app/components/features/reviews.vue").default
export const FeaturesSettings: typeof import("../layers/seller-dashboard-app/app/components/features/settings.vue").default
export const FeaturesSpaces: typeof import("../layers/seller-dashboard-app/app/components/features/spaces.vue").default
export const MagicDrawer: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicDrawer/src/components/MagicDrawer.vue").default
export const MagicMenuChannel: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuChannel.vue").default
export const MagicMenuContent: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuContent.vue").default
export const MagicMenuFloat: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuFloat.vue").default
export const MagicMenuItem: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuItem.vue").default
export const MagicMenuProvider: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuProvider.vue").default
export const MagicMenuRemote: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuRemote.vue").default
export const MagicMenuTrigger: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuTrigger.vue").default
export const MagicMenuView: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuView.vue").default
export const MagicModal: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicModal/src/components/MagicModal.vue").default
export const MagicCommandContent: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandContent.vue").default
export const MagicCommandDrawer: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandDrawer.vue").default
export const MagicCommandItem: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandItem.vue").default
export const MagicCommandModal: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandModal.vue").default
export const MagicCommandProvider: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandProvider.vue").default
export const MagicCommandRenderer: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandRenderer.vue").default
export const MagicCommandTrigger: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandTrigger.vue").default
export const MagicCommandView: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandView.vue").default
export const MagicCookieItem: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieItem.vue").default
export const MagicCookieProvider: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieProvider.vue").default
export const MagicCookieView: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieView.vue").default
export const MagicMarquee: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMarquee/src/components/MagicMarquee.vue").default
export const MagicPlayerAudio: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudio.vue").default
export const MagicPlayerAudioControls: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudioControls.vue").default
export const MagicPlayerDisplayTime: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerDisplayTime.vue").default
export const MagicPlayerMuxPopover: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerMuxPopover.vue").default
export const MagicPlayerOverlay: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerOverlay.vue").default
export const MagicPlayerPoster: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerPoster.vue").default
export const MagicPlayerProvider: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerProvider.vue").default
export const MagicPlayerTimeline: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerTimeline.vue").default
export const MagicPlayerVideo: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideo.vue").default
export const MagicPlayerVideoControls: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideoControls.vue").default
export const MagicScrollCollision: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollCollision.vue").default
export const MagicScrollMotion: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollMotion.vue").default
export const MagicScrollProvider: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollProvider.vue").default
export const MagicScrollScene: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollScene.vue").default
export const AuthState: typeof import("../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue").default
export const Bouncer: typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Bouncer.vue").default
export const Can: typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Can.vue").default
export const Cannot: typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Cannot.vue").default
export const Primitive: typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Primitive").default
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
export const LCircle: typeof import("@vue-leaflet/vue-leaflet").LCircle
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet").LCircleMarker
export const LControl: typeof import("@vue-leaflet/vue-leaflet").LControl
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet").LControlAttribution
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet").LControlLayers
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet").LControlScale
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet").LControlZoom
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet").LFeatureGroup
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet").LGeoJson
export const LIcon: typeof import("@vue-leaflet/vue-leaflet").LIcon
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet").LImageOverlay
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet").LLayerGroup
export const LMap: typeof import("@vue-leaflet/vue-leaflet").LMap
export const LMarker: typeof import("@vue-leaflet/vue-leaflet").LMarker
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet").LPolygon
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet").LPolyline
export const LPopup: typeof import("@vue-leaflet/vue-leaflet").LPopup
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet").LRectangle
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet").LTileLayer
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet").LTooltip
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet").LWmsTileLayer
export const MagicDraggable: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicDraggable/src/components/MagicDraggable.vue").default
export const MagicPie: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPie/src/components/MagicPie.vue").default
export const MagicNoise: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicNoise/src/components/MagicNoise.vue").default
export const MagicToastProvider: typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicToast/src/components/MagicToastProvider.vue").default
export const InstallButton: typeof import("../node_modules/@nuxtjs/mcp-toolkit/dist/runtime/components/InstallButton.vue").default
export const TiptapEditorContent: typeof import("@tiptap/vue-3").EditorContent
export const TiptapFloatingMenu: typeof import("@tiptap/vue-3/menus").FloatingMenu
export const TiptapBubbleMenu: typeof import("@tiptap/vue-3/menus").BubbleMenu
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components").Body
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue").SchemaOrgDebug
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue").SchemaOrgArticle
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue").SchemaOrgComment
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue").SchemaOrgEvent
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue").SchemaOrgHowTo
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue").SchemaOrgImage
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue").SchemaOrgOrganization
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue").SchemaOrgPerson
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue").SchemaOrgProduct
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue").SchemaOrgQuestion
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue").SchemaOrgRecipe
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue").SchemaOrgReview
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue").SchemaOrgVideo
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue").SchemaOrgWebPage
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue").SchemaOrgWebSite
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue").SchemaOrgMovie
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue").SchemaOrgCourse
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue").SchemaOrgItemList
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue").SchemaOrgBook
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyBlocksNewsletter: LazyComponent<typeof import("../app/components/blocks/Newsletter.vue").default>
export const LazyBlocksAgeverification: LazyComponent<typeof import("../app/components/blocks/ageverification.vue").default>
export const LazyBlocksAnnouncements: LazyComponent<typeof import("../app/components/blocks/announcements.vue").default>
export const LazyBlocksCopyright: LazyComponent<typeof import("../app/components/blocks/copyright.vue").default>
export const LazyBlocksEditor: LazyComponent<typeof import("../app/components/blocks/editor.vue").default>
export const LazyBlocksLogo: LazyComponent<typeof import("../app/components/blocks/logo.vue").default>
export const LazyBlocksUseDark: LazyComponent<typeof import("../app/components/blocks/useDark.vue").default>
export const LazyMenusBottomFooter: LazyComponent<typeof import("../app/components/menus/BottomFooter.vue").default>
export const LazyMenusFooterNav: LazyComponent<typeof import("../app/components/menus/FooterNav.vue").default>
export const LazyMenusLayoutNotifications: LazyComponent<typeof import("../app/components/menus/LayoutNotifications.vue").default>
export const LazyMenusLowerBar: LazyComponent<typeof import("../app/components/menus/LowerBar.vue").default>
export const LazyMenusEcosystemmenu: LazyComponent<typeof import("../app/components/menus/ecosystemmenu.vue").default>
export const LazyMenusLivebarLive: LazyComponent<typeof import("../app/components/menus/livebar/live.vue").default>
export const LazyMenusMobilesearch: LazyComponent<typeof import("../app/components/menus/mobilesearch.vue").default>
export const LazyMenusSellerbar: LazyComponent<typeof import("../app/components/menus/sellerbar.vue").default>
export const LazyMenusSidebarBottomsidebarmenu: LazyComponent<typeof import("../app/components/menus/sidebar/bottomsidebarmenu.vue").default>
export const LazyMenusSidebarDepartmentsmenu: LazyComponent<typeof import("../app/components/menus/sidebar/departmentsmenu.vue").default>
export const LazyMenusSidebarMyaccountmenu: LazyComponent<typeof import("../app/components/menus/sidebar/myaccountmenu.vue").default>
export const LazyMenusSidebarOutletsmenu: LazyComponent<typeof import("../app/components/menus/sidebar/outletsmenu.vue").default>
export const LazyMenusSidebarSidebartop: LazyComponent<typeof import("../app/components/menus/sidebar/sidebartop.vue").default>
export const LazyMenusSidebarSocialmenu: LazyComponent<typeof import("../app/components/menus/sidebar/socialmenu.vue").default>
export const LazyMenusSidebarTopmenu: LazyComponent<typeof import("../app/components/menus/sidebar/topmenu.vue").default>
export const LazyMenusSidebarnav: LazyComponent<typeof import("../app/components/menus/sidebarnav.vue").default>
export const LazyMenusSocialLeftmenu: LazyComponent<typeof import("../app/components/menus/social/leftmenu.vue").default>
export const LazyMenusTopmenu: LazyComponent<typeof import("../app/components/menus/topmenu.vue").default>
export const LazyMenusTopmenuCart: LazyComponent<typeof import("../app/components/menus/topmenu/cart.vue").default>
export const LazyMenusTopmenuMobilesearch: LazyComponent<typeof import("../app/components/menus/topmenu/mobilesearch.vue").default>
export const LazyMenusTopmenuMyaccounttopmenu: LazyComponent<typeof import("../app/components/menus/topmenu/myaccounttopmenu.vue").default>
export const LazyPagesHomepageAtaglance: LazyComponent<typeof import("../app/components/pages/homepage/ataglance.vue").default>
export const LazyPagesHomepageBlogcallout: LazyComponent<typeof import("../app/components/pages/homepage/blogcallout.vue").default>
export const LazyPagesHomepageBlogposts: LazyComponent<typeof import("../app/components/pages/homepage/blogposts.vue").default>
export const LazyPagesHomepageBookcallout: LazyComponent<typeof import("../app/components/pages/homepage/bookcallout.vue").default>
export const LazyPagesHomepageCallout: LazyComponent<typeof import("../app/components/pages/homepage/callout.vue").default>
export const LazyPagesHomepageHeaderslider: LazyComponent<typeof import("../app/components/pages/homepage/headerslider.vue").default>
export const LazyPagesHomepageHellobar: LazyComponent<typeof import("../app/components/pages/homepage/hellobar.vue").default>
export const LazyPagesHomepageIntro: LazyComponent<typeof import("../app/components/pages/homepage/intro.vue").default>
export const LazyPagesHomepageMusiccallout: LazyComponent<typeof import("../app/components/pages/homepage/musiccallout.vue").default>
export const LazyPagesHomepagePixanomycallout: LazyComponent<typeof import("../app/components/pages/homepage/pixanomycallout.vue").default>
export const LazyPagesHomepageRadiostationscallout: LazyComponent<typeof import("../app/components/pages/homepage/radiostationscallout.vue").default>
export const LazyPagesHomepageSectionscallout: LazyComponent<typeof import("../app/components/pages/homepage/sectionscallout.vue").default>
export const LazyPagesHomepageSpotlight: LazyComponent<typeof import("../app/components/pages/homepage/spotlight.vue").default>
export const LazyPagesHomepageTheatercallout: LazyComponent<typeof import("../app/components/pages/homepage/theatercallout.vue").default>
export const LazyPagesHomepageYardsale: LazyComponent<typeof import("../app/components/pages/homepage/yardsale.vue").default>
export const LazyPagesNotifications: LazyComponent<typeof import("../app/components/pages/notifications.vue").default>
export const LazyPagesOffline: LazyComponent<typeof import("../app/components/pages/offline.vue").default>
export const LazyPagesProfileArchives: LazyComponent<typeof import("../app/components/pages/profile/archives.vue").default>
export const LazyPagesProfileBookmarks: LazyComponent<typeof import("../app/components/pages/profile/bookmarks.vue").default>
export const LazyPagesProfileLikes: LazyComponent<typeof import("../app/components/pages/profile/likes.vue").default>
export const LazyPagesProfileMedia: LazyComponent<typeof import("../app/components/pages/profile/media.vue").default>
export const LazyPagesProfileReplies: LazyComponent<typeof import("../app/components/pages/profile/replies.vue").default>
export const LazyPagesUpload: LazyComponent<typeof import("../app/components/pages/upload.vue").default>
export const LazyAuthLogutButton: LazyComponent<typeof import("../layers/shared-app/app/components/auth/logutButton.vue").default>
export const LazyCommunicationChannels: LazyComponent<typeof import("../layers/shared-app/app/components/communication/channels.vue").default>
export const LazyCommunicationChat: LazyComponent<typeof import("../layers/shared-app/app/components/communication/chat.vue").default>
export const LazyCommunicationDirectory: LazyComponent<typeof import("../layers/shared-app/app/components/communication/directory.vue").default>
export const LazyCommunicationInvites: LazyComponent<typeof import("../layers/shared-app/app/components/communication/invites.vue").default>
export const LazyCommunicationMessages: LazyComponent<typeof import("../layers/shared-app/app/components/communication/messages.vue").default>
export const LazyCommunicationRooms: LazyComponent<typeof import("../layers/shared-app/app/components/communication/rooms.vue").default>
export const LazyCommunicationTeams: LazyComponent<typeof import("../layers/shared-app/app/components/communication/teams.vue").default>
export const LazyMediaNowPlaying: LazyComponent<typeof import("../layers/shared-app/app/components/media/nowPlaying.vue").default>
export const LazyMediaPlaylist: LazyComponent<typeof import("../layers/shared-app/app/components/media/playlist.vue").default>
export const LazyMediaRadioPlayer: LazyComponent<typeof import("../layers/shared-app/app/components/media/radioPlayer.vue").default>
export const LazyMediaVideoPlayer: LazyComponent<typeof import("../layers/shared-app/app/components/media/videoPlayer.vue").default>
export const LazySearchAtomsBaseButton: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/BaseButton.vue").default>
export const LazySearchAtomsBaseCard: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/BaseCard.vue").default>
export const LazySearchAtomsBaseCheckbox: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/BaseCheckbox.vue").default>
export const LazySearchAtomsBaseLogo: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/BaseLogo.vue").default>
export const LazySearchAtomsBaseText: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/BaseText.vue").default>
export const LazySearchAtomsBaseTitle: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/BaseTitle.vue").default>
export const LazySearchAtomsDiscordIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/DiscordIcon.vue").default>
export const LazySearchAtomsGithubIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/GithubIcon.vue").default>
export const LazySearchAtomsHalfSolidStarIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/HalfSolidStarIcon.vue").default>
export const LazySearchAtomsSelectArrow: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/SelectArrow.vue").default>
export const LazySearchAtomsSolidStarIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/SolidStarIcon.vue").default>
export const LazySearchAtomsStarIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/StarIcon.vue").default>
export const LazySearchAtomsTwitterIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/TwitterIcon.vue").default>
export const LazySearchAtomsWebIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/WebIcon.vue").default>
export const LazySearchAtomsXIcon: LazyComponent<typeof import("../layers/shared-app/app/components/search/atoms/XIcon.vue").default>
export const LazySearchFeaturesAiSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/features/aiSearch.vue").default>
export const LazySearchFeaturesAllSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/features/allSearch.vue").default>
export const LazySearchFeaturesAutocomplete: LazyComponent<typeof import("../layers/shared-app/app/components/search/features/autocomplete.vue").default>
export const LazySearchFeaturesImageSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/features/imageSearch.vue").default>
export const LazySearchFeaturesVideoSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/features/videoSearch.vue").default>
export const LazySearchFilters: LazyComponent<typeof import("../layers/shared-app/app/components/search/filters/filters.vue").default>
export const LazySearchMoleculesBaseSelect: LazyComponent<typeof import("../layers/shared-app/app/components/search/molecules/BaseSelect.vue").default>
export const LazySearchMoleculesPageNumber: LazyComponent<typeof import("../layers/shared-app/app/components/search/molecules/PageNumber.vue").default>
export const LazySearchMoleculesRangeSlider: LazyComponent<typeof import("../layers/shared-app/app/components/search/molecules/RangeSlider.vue").default>
export const LazySearchMoleculesSearchInput: LazyComponent<typeof import("../layers/shared-app/app/components/search/molecules/SearchInput.vue").default>
export const LazySearchMoleculesSocialLink: LazyComponent<typeof import("../layers/shared-app/app/components/search/molecules/SocialLink.vue").default>
export const LazySearchMoleculesStarRating: LazyComponent<typeof import("../layers/shared-app/app/components/search/molecules/StarRating.vue").default>
export const LazySearchOrganismsLoadingIndicator: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/LoadingIndicator.vue").default>
export const LazySearchOrganismsMeiliSearchBar: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchBar.vue").default>
export const LazySearchOrganismsMeiliSearchFacetFilter: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchFacetFilter.vue").default>
export const LazySearchOrganismsMeiliSearchLoadingProvider: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchLoadingProvider.vue").default>
export const LazySearchOrganismsMeiliSearchPagination: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchPagination.vue").default>
export const LazySearchOrganismsMeiliSearchProvider: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchProvider.vue").default>
export const LazySearchOrganismsMeiliSearchRangeFilter: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchRangeFilter.vue").default>
export const LazySearchOrganismsMeiliSearchRatingFilter: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchRatingFilter.vue").default>
export const LazySearchOrganismsMeiliSearchResults: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchResults.vue").default>
export const LazySearchOrganismsMeiliSearchSorting: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchSorting.vue").default>
export const LazySearchOrganismsMeiliSearchStats: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/MeiliSearchStats.vue").default>
export const LazySearchOrganismsProductCard: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/ProductCard.vue").default>
export const LazySearchOrganismsTheNavbar: LazyComponent<typeof import("../layers/shared-app/app/components/search/organisms/TheNavbar.vue").default>
export const LazySearchResultsAudioSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/audioSearch.vue").default>
export const LazySearchResultsBooksSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/booksSearch.vue").default>
export const LazySearchResultsFinanceSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/financeSearch.vue").default>
export const LazySearchResultsImageSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/imageSearch.vue").default>
export const LazySearchResultsMusicSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/musicSearch.vue").default>
export const LazySearchResultsNewsSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/newsSearch.vue").default>
export const LazySearchResultsSpaceSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/spaceSearch.vue").default>
export const LazySearchResultsSpacesSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/spacesSearch.vue").default>
export const LazySearchResultsTravelSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/travelSearch.vue").default>
export const LazySearchResultsVideoSearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/results/videoSearch.vue").default>
export const LazySearch: LazyComponent<typeof import("../layers/shared-app/app/components/search/search.vue").default>
export const LazySearchTemplatesHomeTemplate: LazyComponent<typeof import("../layers/shared-app/app/components/search/templates/HomeTemplate.vue").default>
export const LazySearchWidgetsClearRefinements: LazyComponent<typeof import("../layers/shared-app/app/components/search/widgets/ClearRefinements.vue").default>
export const LazySearchWidgetsNoResults: LazyComponent<typeof import("../layers/shared-app/app/components/search/widgets/NoResults.vue").default>
export const LazyUiPageBuilder: LazyComponent<typeof import("../layers/shared-app/app/components/ui/PageBuilder.vue").default>
export const LazyUiFormsBooleanInput: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/BooleanInput.vue").default>
export const LazyUiFormsDateTime: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/DateTime.vue").default>
export const LazyUiFormsDirectusFormElement: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/DirectusFormElement.vue").default>
export const LazyUiFormsDynamicTableElement: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/DynamicTableElement.vue").default>
export const LazyUiFormsFileInput: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/FileInput.vue").default>
export const LazyUiFormsRelationSelect: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/RelationSelect.vue").default>
export const LazyUiFormsRepeaterInput: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/RepeaterInput.vue").default>
export const LazyUiFormsSelectInput: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/SelectInput.vue").default>
export const LazyUiFormsTextArea: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/TextArea.vue").default>
export const LazyUiFormsTextInput: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/TextInput.vue").default>
export const LazyUiFormsTiptapEditor: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/TiptapEditor.vue").default>
export const LazyUiForms[collection]: LazyComponent<typeof import("../layers/shared-app/app/components/ui/forms/[collection].vue").default>
export const LazyFeaturesAttributes: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/attributes.vue").default>
export const LazyFeaturesIncentives: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/incentives.vue").default>
export const LazyFeaturesIntegrations: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/integrations.vue").default>
export const LazyFeaturesMedia: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/media.vue").default>
export const LazyFeaturesProducts: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/products.vue").default>
export const LazyFeaturesReviews: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/reviews.vue").default>
export const LazyFeaturesSettings: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/settings.vue").default>
export const LazyFeaturesSpaces: LazyComponent<typeof import("../layers/seller-dashboard-app/app/components/features/spaces.vue").default>
export const LazyMagicDrawer: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicDrawer/src/components/MagicDrawer.vue").default>
export const LazyMagicMenuChannel: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuChannel.vue").default>
export const LazyMagicMenuContent: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuContent.vue").default>
export const LazyMagicMenuFloat: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuFloat.vue").default>
export const LazyMagicMenuItem: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuItem.vue").default>
export const LazyMagicMenuProvider: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuProvider.vue").default>
export const LazyMagicMenuRemote: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuRemote.vue").default>
export const LazyMagicMenuTrigger: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuTrigger.vue").default>
export const LazyMagicMenuView: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMenu/src/components/MagicMenuView.vue").default>
export const LazyMagicModal: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicModal/src/components/MagicModal.vue").default>
export const LazyMagicCommandContent: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandContent.vue").default>
export const LazyMagicCommandDrawer: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandDrawer.vue").default>
export const LazyMagicCommandItem: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandItem.vue").default>
export const LazyMagicCommandModal: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandModal.vue").default>
export const LazyMagicCommandProvider: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandProvider.vue").default>
export const LazyMagicCommandRenderer: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandRenderer.vue").default>
export const LazyMagicCommandTrigger: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandTrigger.vue").default>
export const LazyMagicCommandView: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCommand/src/components/MagicCommandView.vue").default>
export const LazyMagicCookieItem: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieItem.vue").default>
export const LazyMagicCookieProvider: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieProvider.vue").default>
export const LazyMagicCookieView: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicCookie/src/components/MagicCookieView.vue").default>
export const LazyMagicMarquee: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicMarquee/src/components/MagicMarquee.vue").default>
export const LazyMagicPlayerAudio: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudio.vue").default>
export const LazyMagicPlayerAudioControls: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerAudioControls.vue").default>
export const LazyMagicPlayerDisplayTime: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerDisplayTime.vue").default>
export const LazyMagicPlayerMuxPopover: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerMuxPopover.vue").default>
export const LazyMagicPlayerOverlay: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerOverlay.vue").default>
export const LazyMagicPlayerPoster: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerPoster.vue").default>
export const LazyMagicPlayerProvider: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerProvider.vue").default>
export const LazyMagicPlayerTimeline: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerTimeline.vue").default>
export const LazyMagicPlayerVideo: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideo.vue").default>
export const LazyMagicPlayerVideoControls: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPlayer/src/components/MagicPlayerVideoControls.vue").default>
export const LazyMagicScrollCollision: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollCollision.vue").default>
export const LazyMagicScrollMotion: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollMotion.vue").default>
export const LazyMagicScrollProvider: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollProvider.vue").default>
export const LazyMagicScrollScene: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicScroll/src/components/MagicScrollScene.vue").default>
export const LazyAuthState: LazyComponent<typeof import("../node_modules/nuxt-auth-utils/dist/runtime/app/components/AuthState.vue").default>
export const LazyBouncer: LazyComponent<typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Bouncer.vue").default>
export const LazyCan: LazyComponent<typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Can.vue").default>
export const LazyCannot: LazyComponent<typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Cannot.vue").default>
export const LazyPrimitive: LazyComponent<typeof import("../node_modules/nuxt-authorization/dist/runtime/components/Primitive").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
export const LazyLCircle: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LCircle>
export const LazyLCircleMarker: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LCircleMarker>
export const LazyLControl: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControl>
export const LazyLControlAttribution: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlAttribution>
export const LazyLControlLayers: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlLayers>
export const LazyLControlScale: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlScale>
export const LazyLControlZoom: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LControlZoom>
export const LazyLFeatureGroup: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LFeatureGroup>
export const LazyLGeoJson: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LGeoJson>
export const LazyLIcon: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LIcon>
export const LazyLImageOverlay: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LImageOverlay>
export const LazyLLayerGroup: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LLayerGroup>
export const LazyLMap: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LMap>
export const LazyLMarker: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LMarker>
export const LazyLPolygon: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LPolygon>
export const LazyLPolyline: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LPolyline>
export const LazyLPopup: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LPopup>
export const LazyLRectangle: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LRectangle>
export const LazyLTileLayer: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LTileLayer>
export const LazyLTooltip: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LTooltip>
export const LazyLWmsTileLayer: LazyComponent<typeof import("@vue-leaflet/vue-leaflet").LWmsTileLayer>
export const LazyMagicDraggable: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicDraggable/src/components/MagicDraggable.vue").default>
export const LazyMagicPie: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicPie/src/components/MagicPie.vue").default>
export const LazyMagicNoise: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicNoise/src/components/MagicNoise.vue").default>
export const LazyMagicToastProvider: LazyComponent<typeof import("../node_modules/@maas/vue-equipment/dist/plugins/MagicToast/src/components/MagicToastProvider.vue").default>
export const LazyInstallButton: LazyComponent<typeof import("../node_modules/@nuxtjs/mcp-toolkit/dist/runtime/components/InstallButton.vue").default>
export const LazyTiptapEditorContent: LazyComponent<typeof import("@tiptap/vue-3").EditorContent>
export const LazyTiptapFloatingMenu: LazyComponent<typeof import("@tiptap/vue-3/menus").FloatingMenu>
export const LazyTiptapBubbleMenu: LazyComponent<typeof import("@tiptap/vue-3/menus").BubbleMenu>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazySchemaOrgDebug: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgDebug>
export const LazySchemaOrgArticle: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgArticle>
export const LazySchemaOrgBreadcrumb: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb>
export const LazySchemaOrgComment: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgComment>
export const LazySchemaOrgEvent: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgEvent>
export const LazySchemaOrgFoodEstablishment: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment>
export const LazySchemaOrgHowTo: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgHowTo>
export const LazySchemaOrgImage: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgImage>
export const LazySchemaOrgJobPosting: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting>
export const LazySchemaOrgLocalBusiness: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness>
export const LazySchemaOrgOrganization: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgOrganization>
export const LazySchemaOrgPerson: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgPerson>
export const LazySchemaOrgProduct: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgProduct>
export const LazySchemaOrgQuestion: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgQuestion>
export const LazySchemaOrgRecipe: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgRecipe>
export const LazySchemaOrgReview: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgReview>
export const LazySchemaOrgVideo: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgVideo>
export const LazySchemaOrgWebPage: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebPage>
export const LazySchemaOrgWebSite: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebSite>
export const LazySchemaOrgMovie: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgMovie>
export const LazySchemaOrgCourse: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgCourse>
export const LazySchemaOrgItemList: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgItemList>
export const LazySchemaOrgBook: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBook>
export const LazySchemaOrgSoftwareApp: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
